/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExternoPanelFktercero.java
 *
 * Created on 16/02/2012, 09:45:23 PM
 */
package frame;

import clases.ClaseGeneral;
import clases.ClaseInformacion;
import clases.ClaseInformes;
import clases.ClaseMensaje;
import entidades.Observacionescontratos;
import entidades.ObservacionescontratosPK;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jhon Lopez
 */
public class ExternoPanelAccionesContratos extends javax.swing.JPanel {

    private FrameCarga frameCarga = new FrameCarga();
    private Thread hilo = new ThreadCarga();

    /**
     * Creates new form ExternoPanelFktercero
     */
    public ExternoPanelAccionesContratos() {
        initComponents();

        fkcontrato.setText(ClaseGeneral.contratos.getContrato());
        if (ClaseGeneral.perfil.equals("usuario")) {
            observacion.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fkcontrato = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        dependencia = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        accion = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        observacion = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(550, 340));
        setMinimumSize(new java.awt.Dimension(550, 340));
        setPreferredSize(new java.awt.Dimension(550, 340));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setBackground(ClaseGeneral.titulo);
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Acciones Contrato");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(540, 25));
        add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setPreferredSize(new java.awt.Dimension(540, 10));
        add(jLabel2);

        jLabel3.setText("NÚMERO DEL CONTRATO : ");
        jLabel3.setPreferredSize(new java.awt.Dimension(160, 25));
        add(jLabel3);

        fkcontrato.setBackground(ClaseGeneral.verde);
        fkcontrato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fkcontrato.setForeground(new java.awt.Color(255, 0, 0));
        fkcontrato.setFocusable(false);
        fkcontrato.setMargin(new java.awt.Insets(2, 4, 2, 4));
        fkcontrato.setPreferredSize(new java.awt.Dimension(300, 25));
        add(fkcontrato);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setEnabled(false);
        jTextField1.setFocusable(false);
        jTextField1.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField1.setOpaque(false);
        jTextField1.setPreferredSize(new java.awt.Dimension(70, 25));
        add(jTextField1);

        jLabel48.setText("DEPENDENCIA : ");
        jLabel48.setPreferredSize(new java.awt.Dimension(100, 25));
        add(jLabel48);

        dependencia.setBackground(ClaseGeneral.campo);
        dependencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dependencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "ARTES GRAFICAS", "DECANATO", "DEPARTAMENTO DE BIOLOGIA", "DEPARTAMENTO DE FISICA", "DEPARTAMENTO DE MATEMATICAS", "DEPARTAMENTO DE QUIMICA" }));
        dependencia.setSelectedItem("COORDINACIÓN DE ÁREA ADMINISTRATIVA");
        dependencia.setPreferredSize(new java.awt.Dimension(300, 25));
        //dependencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "COORDINACIÓN DE ÁREA ADMINISTRATIVA", "VICE-DECANATURA DE INVESTIGACIONES", "ESCUELA DE INGENIERIA INDUSTRIAL" }));
        add(dependencia);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setEnabled(false);
        jTextField2.setFocusable(false);
        jTextField2.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField2.setOpaque(false);
        jTextField2.setPreferredSize(new java.awt.Dimension(130, 25));
        add(jTextField2);

        jLabel4.setText("ACCION A REALIZAR : ");
        jLabel4.setPreferredSize(new java.awt.Dimension(135, 25));
        add(jLabel4);

        accion.setBackground(ClaseGeneral.campo);
        accion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        accion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ENVIAR A DEPENDENCIA", "DEVOLVER A DEPENDENCIA", "DOCUMENTO DIGITALIZADO" }));
        accion.setPreferredSize(new java.awt.Dimension(400, 25));
        add(accion);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setPreferredSize(new java.awt.Dimension(540, 10));
        add(jLabel5);

        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 20));
        jSeparator1.setPreferredSize(new java.awt.Dimension(540, 10));
        add(jSeparator1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OBSERVACIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(540, 150));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane.setPreferredSize(new java.awt.Dimension(430, 70));

        observacion.setBackground(ClaseGeneral.campo);
        observacion.setColumns(20);
        observacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        observacion.setLineWrap(true);
        observacion.setRows(15);
        observacion.setWrapStyleWord(true);
        observacion.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jScrollPane.setViewportView(observacion);

        jPanel5.add(jScrollPane, java.awt.BorderLayout.CENTER);

        add(jPanel5);
    }// </editor-fold>//GEN-END:initComponents

    public void metodoInsertar() {
        if (accion.getSelectedItem().toString().equals("ENVIAR A DEPENDENCIA")) {
            observacion.setText("PENDIENTE\nENVIAR A DEPENDENCIA\n" + observacion.getText());
        } else if (accion.getSelectedItem().toString().equals("DEVOLVER A DEPENDENCIA")) {
            observacion.setText("PENDIENTE\nDEVOLVER A DEPENDENCIA\n" + observacion.getText());
        } else {
            observacion.setText("DOCUMENTO DIGITALIZADO\n"
                    + observacion.getText());
        }
        ClaseGeneral.observacionescontratos = new Observacionescontratos();
        ClaseGeneral.observacionescontratosPK = new ObservacionescontratosPK();
        ClaseGeneral.observacionescontratosPK.setFkcontrato(fkcontrato.getText());
        ClaseGeneral.observacionescontratos.setObservacionescontratosPK(ClaseGeneral.observacionescontratosPK);
        ClaseGeneral.observacionescontratos.setDependencia("" + dependencia.getSelectedItem());
        ClaseGeneral.observacionescontratos.setObservacion(observacion.getText().toUpperCase());

        try {
            ClaseGeneral.controlObservacionescontratos.createTimestamp(ClaseGeneral.observacionescontratos);

            try {
                frameCarga.setVisible(true);
                frameCarga.pack();
                frameCarga.setSize(280, 100);
                frameCarga.setLocationRelativeTo(null);
                frameCarga.setResizable(false);
                hilo = new ThreadCarga();
                hilo.start();
            } catch (Exception e) {
            }
        } catch (Exception ex) {
            Logger.getLogger(PanelObservacionescontratos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    class ThreadCarga extends Thread {

        @Override
        public void run() {
            frameCarga.jProgressBar.setIndeterminate(true);
            frameCarga.jProgressBar.setMinimum(1);
            frameCarga.jProgressBar.setMaximum(100);
            /**
             *
             */

            try {
                Observacionescontratos observacionescontratos = ClaseGeneral.controlObservacionescontratos.findAllInObservacionescontratosByFkcontratoMAXfecha(ClaseGeneral.contratos.getContrato());

                Map parametros = new HashMap();
                parametros.put("DEPENDENCIA", observacionescontratos.getDependencia());
                parametros.put("FECHA", ClaseInformacion.ConvertirFecha(observacionescontratos.getObservacionescontratosPK().getFecha()));
                parametros.put("OBSERVACION", (observacionescontratos.getObservacion().contains("DEVOLVER A DEPENDENCIA")
                        ? observacionescontratos.getObservacion().substring(32)
                        : observacionescontratos.getObservacion()));
                parametros.put("SOPORTE", observacionescontratos.getObservacionescontratosPK().getFkcontrato());
                parametros.put("MONTO", ClaseGeneral.contratos.getValor());
                parametros.put("TIPO", ClaseGeneral.controlSoportescontratos.findTipoInSoportescontratosByFkcontratoRESGITRO(observacionescontratos.getObservacionescontratosPK().getFkcontrato()));

                ClaseInformes informes = new ClaseInformes();
                if (ClaseGeneral.observacionescontratos.getObservacion().contains("ENVIAR A DEPENDENCIA")) {
                    informes.formatoCondicionContratos(parametros);
                } else if (ClaseGeneral.observacionescontratos.getObservacion().contains("DOCUMENTO DIGITALIZADO")) {
                    informes.formatoCondicionContratosDigitalizados(parametros);
                } else {
                    informes.formatoCondicion(parametros);
                }
            } catch (Exception e) {
                ClaseMensaje.error("Error al mostrar el archivo.\n" + e);
            }

            /**
             *
             */
            frameCarga.jProgressBar.setIndeterminate(false);
            frameCarga.dispose();
            hilo = null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox accion;
    private javax.swing.JComboBox dependencia;
    private javax.swing.JTextField fkcontrato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextArea observacion;
    // End of variables declaration//GEN-END:variables
}
