/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExternoPanelFktercero.java
 *
 * Created on 16/02/2012, 09:45:23 PM
 */
package frame;

import clases.ClaseGeneral;
import entidades.Solicitudesoferta;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author Jhon Lopez
 */
public class ExternoPanelBuscarSolicitudesOferta extends javax.swing.JPanel {

    public List listaSolicitudesOferta = new ArrayList();
    public String solicitudesoferta = "";
    public int posicion;
    private PanelSolicitudesOferta panelSolicitudesOferta = new PanelSolicitudesOferta();

    /**
     * Creates new form ExternoPanelFktercero
     */
    public ExternoPanelBuscarSolicitudesOferta(PanelSolicitudesOferta panelSolicitudesOferta) {
        initComponents();
        this.panelSolicitudesOferta = panelSolicitudesOferta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        parametro = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        texto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        scrollLista = new javax.swing.JScrollPane();
        lista = new javax.swing.JList();

        setMaximumSize(new java.awt.Dimension(550, 300));
        setMinimumSize(new java.awt.Dimension(550, 300));
        setPreferredSize(new java.awt.Dimension(550, 300));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setBackground(ClaseGeneral.titulo);
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Criterios de Búsqueda");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(540, 25));
        add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setPreferredSize(new java.awt.Dimension(540, 10));
        add(jLabel2);

        jLabel3.setText("CRITERIO : ");
        jLabel3.setPreferredSize(new java.awt.Dimension(90, 25));
        add(jLabel3);

        parametro.setBackground(ClaseGeneral.campo);
        parametro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parametro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NÚMERO DE SOLICITUD [CAST(solicitudesoferta.id AS TEXT)]", "CÉDULA DEL PROVEEDOR [fktercero]", "NÚMERO DE CERTIFICADO [CAST(solicitudesoferta.numerocertificado AS TEXT)]", "INFORMACIÓN SERVICIO [informacionservicio]" }));
        parametro.setSelectedItem("COORDINACIÓN DE ÁREA ADMINISTRATIVA");
        parametro.setPreferredSize(new java.awt.Dimension(445, 25));
        parametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parametroActionPerformed(evt);
            }
        });
        add(parametro);

        jLabel4.setText("TEXTO : ");
        jLabel4.setPreferredSize(new java.awt.Dimension(65, 25));
        add(jLabel4);

        texto.setBackground(ClaseGeneral.campo);
        texto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texto.setMargin(new java.awt.Insets(2, 4, 2, 4));
        texto.setPreferredSize(new java.awt.Dimension(470, 25));
        texto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldTextoKeyReleased(evt);
            }
        });
        add(texto);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setPreferredSize(new java.awt.Dimension(540, 10));
        add(jLabel5);

        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 20));
        jSeparator1.setPreferredSize(new java.awt.Dimension(540, 10));
        add(jSeparator1);

        scrollLista.setMaximumSize(new java.awt.Dimension(540, 150));
        scrollLista.setMinimumSize(new java.awt.Dimension(540, 150));
        scrollLista.setPreferredSize(new java.awt.Dimension(540, 150));

        lista.setSelectionBackground(ClaseGeneral.campo);
        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        scrollLista.setViewportView(lista);

        add(scrollLista);
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldTextoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldTextoKeyReleased
        javax.swing.JTextField componente = (javax.swing.JTextField) evt.getComponent();
        String text = componente.getText();
        componente.setText(text.toUpperCase());

        ClaseGeneral.parametro = parametro.getSelectedItem().toString().substring(parametro.getSelectedItem().toString().indexOf("[") + 1, parametro.getSelectedItem().toString().indexOf("]"));
        ClaseGeneral.valor = componente.getText();
        listaSolicitudesOferta = ClaseGeneral.controlSolicitudesoferta.findAllInSolicitudesofertaAndBienessolicitudofertaBy();

        DefaultListModel modeloLista = new DefaultListModel();
        for (int i = 0; i < listaSolicitudesOferta.size(); i++) {
            ClaseGeneral.solicitudesoferta = (Solicitudesoferta) listaSolicitudesOferta.get(i);
            modeloLista.addElement(ClaseGeneral.solicitudesoferta.getId() + " - " + ClaseGeneral.solicitudesoferta.getAno());
        }

        lista.setModel(modeloLista);
}//GEN-LAST:event_TextFieldTextoKeyReleased

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }

        JList laLista = (JList) evt.getSource();
        if (laLista.isSelectionEmpty()) {
            solicitudesoferta = "";
            posicion = -1;
            return;
        } else {
            solicitudesoferta = "" + laLista.getSelectedValue();
            posicion = laLista.getSelectedIndex();
            ClaseGeneral.solicitudesoferta = (Solicitudesoferta) listaSolicitudesOferta.get(posicion);
            panelSolicitudesOferta.metodoConsultar();
        }
}//GEN-LAST:event_listaValueChanged

    private void parametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parametroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parametroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList lista;
    private javax.swing.JComboBox parametro;
    private javax.swing.JScrollPane scrollLista;
    private javax.swing.JTextField texto;
    // End of variables declaration//GEN-END:variables
}
