/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExternoPanelFktercero.java
 *
 * Created on 16/02/2012, 09:45:23 PM
 */
package frame;

import clases.ClaseGeneral;
import clases.ClaseMensaje;
import entidades.Calificacion;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jhon Lopez
 */
public class ExternoPanelCalificacionTramites extends javax.swing.JPanel {
    
    /**
     * Creates new form ExternoPanelFktercero
     */
    public ExternoPanelCalificacionTramites() {
        initComponents();

        tramite.setText(ClaseGeneral.cuentas.getSoporte());
        fktercero.setText(ClaseGeneral.cuentas.getFktercero());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tramite = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fktercero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        observacion = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        botonAyuda1 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        pregunta1 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        pregunta2 = new javax.swing.JComboBox();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        pregunta3 = new javax.swing.JComboBox();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        botonAyuda4 = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        pregunta4 = new javax.swing.JComboBox();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        botonAyuda5 = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        pregunta5 = new javax.swing.JComboBox();
        jTextField7 = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(550, 340));
        setMinimumSize(new java.awt.Dimension(550, 340));
        setPreferredSize(new java.awt.Dimension(550, 630));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setBackground(ClaseGeneral.titulo);
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calificación Tramites");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(540, 25));
        add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setPreferredSize(new java.awt.Dimension(540, 10));
        add(jLabel2);

        jLabel3.setText("TRAMITE : ");
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 25));
        add(jLabel3);

        tramite.setBackground(ClaseGeneral.verde);
        tramite.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tramite.setForeground(new java.awt.Color(255, 0, 0));
        tramite.setFocusable(false);
        tramite.setMargin(new java.awt.Insets(2, 4, 2, 4));
        tramite.setPreferredSize(new java.awt.Dimension(300, 25));
        add(tramite);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setEnabled(false);
        jTextField1.setFocusable(false);
        jTextField1.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField1.setOpaque(false);
        jTextField1.setPreferredSize(new java.awt.Dimension(150, 25));
        add(jTextField1);

        jLabel6.setText("TERCERO : ");
        jLabel6.setPreferredSize(new java.awt.Dimension(80, 25));
        add(jLabel6);

        fktercero.setBackground(ClaseGeneral.verde);
        fktercero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fktercero.setForeground(new java.awt.Color(255, 0, 0));
        fktercero.setFocusable(false);
        fktercero.setMargin(new java.awt.Insets(2, 4, 2, 4));
        fktercero.setPreferredSize(new java.awt.Dimension(455, 25));
        add(fktercero);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setPreferredSize(new java.awt.Dimension(540, 10));
        add(jLabel5);

        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 20));
        jSeparator1.setPreferredSize(new java.awt.Dimension(540, 10));
        add(jSeparator1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OBSERVACIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(540, 150));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane.setPreferredSize(new java.awt.Dimension(430, 70));

        observacion.setBackground(ClaseGeneral.campo);
        observacion.setColumns(20);
        observacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        observacion.setLineWrap(true);
        observacion.setRows(15);
        observacion.setWrapStyleWord(true);
        observacion.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jScrollPane.setViewportView(observacion);

        jPanel5.add(jScrollPane, java.awt.BorderLayout.CENTER);

        add(jPanel5);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setPreferredSize(new java.awt.Dimension(540, 10));
        add(jLabel7);

        jSeparator2.setMinimumSize(new java.awt.Dimension(50, 20));
        jSeparator2.setPreferredSize(new java.awt.Dimension(540, 10));
        add(jSeparator2);

        jLabel10.setText("<html><p style=\"text-align: justify\"><b>1. </b>Como califica usted el servicio <b>pre-venta</b> del tercero ?</p></html>");
        jLabel10.setPreferredSize(new java.awt.Dimension(540, 25));
        add(jLabel10);

        botonAyuda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos24/info.png"))); // NOI18N
        botonAyuda1.setFocusable(false);
        botonAyuda1.setPreferredSize(new java.awt.Dimension(25, 24));
        botonAyuda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAyuda1ActionPerformed(evt);
            }
        });
        add(botonAyuda1);

        jLabel48.setText("CALIFICACIÓN : ");
        jLabel48.setPreferredSize(new java.awt.Dimension(100, 25));
        add(jLabel48);

        pregunta1.setBackground(ClaseGeneral.campo);
        pregunta1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pregunta1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Malísimo (1)", "Malo (2)", "Ni bueno ni malo (3)", "Bueno (4)", "Excelente (5)" }));
        pregunta1.setSelectedItem("COORDINACIÓN DE ÁREA ADMINISTRATIVA");
        pregunta1.setPreferredSize(new java.awt.Dimension(300, 25));
        add(pregunta1);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setEnabled(false);
        jTextField2.setFocusable(false);
        jTextField2.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField2.setOpaque(false);
        jTextField2.setPreferredSize(new java.awt.Dimension(100, 25));
        add(jTextField2);

        jLabel12.setText("<html><p style=\"text-align: justify\"><b>2. </b>Que tan importante fue el <b>precio</b> al momento de elegir el producto/servicio ?</p></html>");
        jLabel12.setPreferredSize(new java.awt.Dimension(510, 25));
        add(jLabel12);

        jLabel50.setText("CALIFICACIÓN : ");
        jLabel50.setPreferredSize(new java.awt.Dimension(100, 25));
        add(jLabel50);

        pregunta2.setBackground(ClaseGeneral.campo);
        pregunta2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pregunta2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Nada importante (1)", "Poco importante (2)", "Moderadamente importante (3)", "Muy importante (4)", "Extremadamente importante (5)" }));
        pregunta2.setSelectedItem("COORDINACIÓN DE ÁREA ADMINISTRATIVA");
        pregunta2.setPreferredSize(new java.awt.Dimension(300, 25));
        add(pregunta2);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField4.setEnabled(false);
        jTextField4.setFocusable(false);
        jTextField4.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField4.setOpaque(false);
        jTextField4.setPreferredSize(new java.awt.Dimension(130, 25));
        add(jTextField4);

        jLabel13.setText("<html><p style=\"text-align: justify\"><b>3. </b>Que tan importante fue la <b>calidad</b> al momento de elegir el producto/servicio ?</p></html>");
        jLabel13.setPreferredSize(new java.awt.Dimension(510, 25));
        add(jLabel13);

        jLabel51.setText("CALIFICACIÓN : ");
        jLabel51.setPreferredSize(new java.awt.Dimension(100, 25));
        add(jLabel51);

        pregunta3.setBackground(ClaseGeneral.campo);
        pregunta3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pregunta3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Nada de influencia (1)", "Poca influencia (2)", "Suficiente influencia (3)", "Mucha influencia (4)", "Demasiada influencia (5)" }));
        pregunta3.setSelectedItem("COORDINACIÓN DE ÁREA ADMINISTRATIVA");
        pregunta3.setPreferredSize(new java.awt.Dimension(300, 25));
        add(pregunta3);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField5.setEnabled(false);
        jTextField5.setFocusable(false);
        jTextField5.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField5.setOpaque(false);
        jTextField5.setPreferredSize(new java.awt.Dimension(130, 25));
        add(jTextField5);

        jLabel14.setText("<html><p style=\"text-align: justify\"><b>4. </b>Como califica usted el servicio de <b>venta</b> ?</p></html>");
        jLabel14.setPreferredSize(new java.awt.Dimension(540, 25));
        add(jLabel14);

        botonAyuda4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos24/info.png"))); // NOI18N
        botonAyuda4.setFocusable(false);
        botonAyuda4.setPreferredSize(new java.awt.Dimension(25, 24));
        botonAyuda4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAyuda4ActionPerformed(evt);
            }
        });
        add(botonAyuda4);

        jLabel52.setText("CALIFICACIÓN : ");
        jLabel52.setPreferredSize(new java.awt.Dimension(100, 25));
        add(jLabel52);

        pregunta4.setBackground(ClaseGeneral.campo);
        pregunta4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pregunta4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Malísimo (1)", "Malo (2)", "Ni bueno ni malo (3)", "Bueno (4)", "Excelente (5)" }));
        pregunta4.setSelectedItem("COORDINACIÓN DE ÁREA ADMINISTRATIVA");
        pregunta4.setPreferredSize(new java.awt.Dimension(300, 25));
        add(pregunta4);

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField6.setEnabled(false);
        jTextField6.setFocusable(false);
        jTextField6.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField6.setOpaque(false);
        jTextField6.setPreferredSize(new java.awt.Dimension(100, 25));
        add(jTextField6);

        jLabel15.setText("<html><p style=\"text-align: justify\"><b>5. </b>Como califica usted el servicio de <b>post-venta</b> ?</p></html>");
        jLabel15.setPreferredSize(new java.awt.Dimension(540, 25));
        add(jLabel15);

        botonAyuda5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos24/info.png"))); // NOI18N
        botonAyuda5.setFocusable(false);
        botonAyuda5.setPreferredSize(new java.awt.Dimension(25, 24));
        botonAyuda5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAyuda5ActionPerformed(evt);
            }
        });
        add(botonAyuda5);

        jLabel53.setText("CALIFICACIÓN : ");
        jLabel53.setPreferredSize(new java.awt.Dimension(100, 25));
        add(jLabel53);

        pregunta5.setBackground(ClaseGeneral.campo);
        pregunta5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pregunta5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Malísimo (1)", "Malo (2)", "Ni bueno ni malo (3)", "Bueno (4)", "Excelente (5)" }));
        pregunta5.setSelectedItem("COORDINACIÓN DE ÁREA ADMINISTRATIVA");
        pregunta5.setPreferredSize(new java.awt.Dimension(300, 25));
        add(pregunta5);

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField7.setEnabled(false);
        jTextField7.setFocusable(false);
        jTextField7.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField7.setOpaque(false);
        jTextField7.setPreferredSize(new java.awt.Dimension(100, 25));
        add(jTextField7);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAyuda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAyuda1ActionPerformed
        ClaseMensaje.informacion("<html><body>"
            + "Temas como contacto con el vendedor, atención de vendedor a sus inquietudes, tramite de documentos pre-contractuales, elaboración de cotización y demás"
            + "</body></html>");
    }//GEN-LAST:event_botonAyuda1ActionPerformed

    private void botonAyuda4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAyuda4ActionPerformed
        ClaseMensaje.informacion("<html><body>"
            + "Temas como facturación, envió de productos, prestación del servicio y demás"
            + "</body></html>");
    }//GEN-LAST:event_botonAyuda4ActionPerformed

    private void botonAyuda5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAyuda5ActionPerformed
        ClaseMensaje.informacion("<html><body>"
            + "Temas como garantia, devoluciones y/o mantenimiento del equipo"
            + "</body></html>");
    }//GEN-LAST:event_botonAyuda5ActionPerformed

    public void metodoInsertar() {
        ClaseGeneral.calificacion = new Calificacion();
        ClaseGeneral.calificacion.setFktercero(fktercero.getText());
        ClaseGeneral.calificacion.setTramite(tramite.getText());
        ClaseGeneral.calificacion.setFecha(ClaseGeneral.cuentas.getFechapresupuestal());
        ClaseGeneral.calificacion.setDescripcion(ClaseGeneral.cuentas.getDescripcion());
        ClaseGeneral.calificacion.setValor(ClaseGeneral.cuentas.getEgreso());
        ClaseGeneral.calificacion.setObservacion(observacion.getText().toUpperCase());
        ClaseGeneral.calificacion.setPregunta1(pregunta1.getSelectedIndex());
        ClaseGeneral.calificacion.setPregunta2(pregunta2.getSelectedIndex());
        ClaseGeneral.calificacion.setPregunta3(pregunta2.getSelectedIndex());
        ClaseGeneral.calificacion.setPregunta4(pregunta3.getSelectedIndex());
        ClaseGeneral.calificacion.setPregunta5(pregunta4.getSelectedIndex());

        try {
            ClaseGeneral.controlCalificacion.create(ClaseGeneral.calificacion);
        } catch (Exception ex) {
            Logger.getLogger(PanelObservacionescontratos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAyuda1;
    private javax.swing.JButton botonAyuda4;
    private javax.swing.JButton botonAyuda5;
    private javax.swing.JTextField fktercero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextArea observacion;
    private javax.swing.JComboBox pregunta1;
    private javax.swing.JComboBox pregunta2;
    private javax.swing.JComboBox pregunta3;
    private javax.swing.JComboBox pregunta4;
    private javax.swing.JComboBox pregunta5;
    private javax.swing.JTextField tramite;
    // End of variables declaration//GEN-END:variables
}
