/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelComprobantes.java
 *
 * Created on 16/01/2012, 05:14:48 PM
 */
package frame;

import clases.ClaseGeneral;
import clases.ClaseInformacion;
import clases.ClaseMensaje;
import entidades.Comprobantes;
import entidades.Soportescomprobantes;
import java.math.BigDecimal;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jhon Lopez
 */
public class PanelComprobantes extends javax.swing.JPanel {

    private List lista = new ArrayList();
    private List listaCALC = new ArrayList();
    private ClaseInformacion informacion = new ClaseInformacion();
    private String estado = "";

    /**
     * Creates new form PanelComprobantes
     */
    public PanelComprobantes() {
        initComponents();

        fechaaplicacion.setFormats(new SimpleDateFormat("yyyy-MM-dd"));
        fechaelaboracion.setFormats(new SimpleDateFormat("yyyy-MM-dd"));
        fechapago.setFormats(new SimpleDateFormat("yyyy-MM-dd"));

        fechaaplicacion.setDate(new Date(100, 0, 1));
        fechaelaboracion.setDate(new Date(ClaseInformacion.calendario.getTimeInMillis()));
        fechapago.setDate(new Date(ClaseInformacion.calendario.getTimeInMillis()));

        ano.setText(ClaseGeneral.controlUtilidades.anoServidor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBalanceSoportes = new javax.swing.JPanel();
        scrollPaneBalanceSoportes = new javax.swing.JScrollPane();
        textAreaBalanceSoportes = new javax.swing.JTextArea();
        jLabelId = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        fechaelaboracion = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        ano = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelFktercero = new javax.swing.JLabel();
        fktercero = new javax.swing.JTextField();
        botonBuscarFktercero = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelValor = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabelFktercerofuncionario = new javax.swing.JLabel();
        fktercerofuncionario = new javax.swing.JTextField();
        botonBuscarFktercerofuncionario = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabelTipopago = new javax.swing.JLabel();
        tipopago = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        fechapago = new org.jdesktop.swingx.JXDatePicker();
        jTextField2 = new javax.swing.JTextField();
        jLabelComprobante = new javax.swing.JLabel();
        comprobante = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        fechaaplicacion = new org.jdesktop.swingx.JXDatePicker();
        jTextField3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanelObservacion = new javax.swing.JPanel();
        jScrollObservacion = new javax.swing.JScrollPane();
        observacion = new javax.swing.JTextArea();
        jLabeL16 = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jScrollPaneSoportesComprobantes = new javax.swing.JScrollPane();
        jTableSoportesComprobantes = new javax.swing.JTable();
        jTextField16 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        valorTotal = new javax.swing.JTextField();

        panelBalanceSoportes.setMinimumSize(new java.awt.Dimension(750, 250));
        panelBalanceSoportes.setPreferredSize(new java.awt.Dimension(750, 250));
        panelBalanceSoportes.setLayout(new java.awt.BorderLayout());

        scrollPaneBalanceSoportes.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        textAreaBalanceSoportes.setEditable(false);
        textAreaBalanceSoportes.setColumns(20);
        textAreaBalanceSoportes.setLineWrap(true);
        textAreaBalanceSoportes.setRows(5);
        textAreaBalanceSoportes.setWrapStyleWord(true);
        textAreaBalanceSoportes.setMargin(new java.awt.Insets(10, 10, 10, 10));
        scrollPaneBalanceSoportes.setViewportView(textAreaBalanceSoportes);

        panelBalanceSoportes.add(scrollPaneBalanceSoportes, java.awt.BorderLayout.CENTER);

        setName("panelComprobantes"); // NOI18N
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelId.setText("NÚMERO DE SOLICITUD : ");
        jLabelId.setPreferredSize(new java.awt.Dimension(155, 25));
        add(jLabelId);

        id.setBackground(ClaseGeneral.verde);
        id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        id.setForeground(ClaseGeneral.rojo);
        id.setText("0");
        id.setFocusable(false);
        id.setMargin(new java.awt.Insets(2, 4, 2, 4));
        id.setPreferredSize(new java.awt.Dimension(150, 25));
        add(id);

        jLabel1.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jLabel1);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jSeparator1);

        jLabel2.setText("FECHA SOLICITUD : ");
        jLabel2.setPreferredSize(new java.awt.Dimension(125, 25));
        add(jLabel2);

        fechaelaboracion.setFocusable(false);
        fechaelaboracion.setMaximumSize(new java.awt.Dimension(120, 25));
        fechaelaboracion.setMinimumSize(new java.awt.Dimension(120, 25));
        fechaelaboracion.setPreferredSize(new java.awt.Dimension(120, 25));
        add(fechaelaboracion);

        jLabel3.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jLabel3);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jSeparator2);

        jLabel4.setText("AÑO : ");
        jLabel4.setPreferredSize(new java.awt.Dimension(60, 25));
        add(jLabel4);

        ano.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ano.setText("0");
        ano.setMargin(new java.awt.Insets(2, 4, 2, 4));
        ano.setPreferredSize(new java.awt.Dimension(75, 25));
        ano.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldFocusGained(evt);
            }
        });
        add(ano);

        jLabel5.setPreferredSize(new java.awt.Dimension(810, 10));
        add(jLabel5);

        jLabelFktercero.setText("CÉDULA DEL PROVEEDOR : ");
        jLabelFktercero.setPreferredSize(new java.awt.Dimension(170, 25));
        add(jLabelFktercero);

        fktercero.setBackground(ClaseGeneral.campo);
        fktercero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fktercero.setFocusable(false);
        fktercero.setMargin(new java.awt.Insets(2, 4, 2, 4));
        fktercero.setPreferredSize(new java.awt.Dimension(585, 25));
        add(fktercero);

        botonBuscarFktercero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos24/search.png"))); // NOI18N
        botonBuscarFktercero.setFocusable(false);
        botonBuscarFktercero.setName("botonBuscarFktercero"); // NOI18N
        botonBuscarFktercero.setPreferredSize(new java.awt.Dimension(25, 24));
        botonBuscarFktercero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarFkterceroActionPerformed(evt);
            }
        });
        add(botonBuscarFktercero);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setEnabled(false);
        jTextField1.setFocusable(false);
        jTextField1.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField1.setOpaque(false);
        jTextField1.setPreferredSize(new java.awt.Dimension(15, 25));
        add(jTextField1);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField4.setEnabled(false);
        jTextField4.setFocusable(false);
        jTextField4.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField4.setOpaque(false);
        jTextField4.setPreferredSize(new java.awt.Dimension(525, 25));
        add(jTextField4);

        jLabel8.setPreferredSize(new java.awt.Dimension(15, 25));
        add(jLabel8);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jSeparator4);

        jLabelValor.setText("VALOR : ");
        jLabelValor.setPreferredSize(new java.awt.Dimension(60, 25));
        add(jLabelValor);

        valor.setBackground(ClaseGeneral.campo);
        valor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valor.setText("0");
        valor.setMargin(new java.awt.Insets(2, 4, 2, 4));
        valor.setPreferredSize(new java.awt.Dimension(170, 25));
        valor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldFocusGained(evt);
            }
        });
        valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TexyFieldKeyReleased(evt);
            }
        });
        add(valor);

        jLabel9.setPreferredSize(new java.awt.Dimension(810, 10));
        add(jLabel9);

        jLabelFktercerofuncionario.setText("CÉDULA DE QUIEN SOLICITA  : ");
        jLabelFktercerofuncionario.setPreferredSize(new java.awt.Dimension(190, 25));
        add(jLabelFktercerofuncionario);

        fktercerofuncionario.setBackground(ClaseGeneral.campo);
        fktercerofuncionario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fktercerofuncionario.setFocusable(false);
        fktercerofuncionario.setMargin(new java.awt.Insets(2, 4, 2, 4));
        fktercerofuncionario.setPreferredSize(new java.awt.Dimension(585, 25));
        add(fktercerofuncionario);

        botonBuscarFktercerofuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos24/search.png"))); // NOI18N
        botonBuscarFktercerofuncionario.setFocusable(false);
        botonBuscarFktercerofuncionario.setName("botonBuscarFktercerofuncionario"); // NOI18N
        botonBuscarFktercerofuncionario.setPreferredSize(new java.awt.Dimension(25, 24));
        botonBuscarFktercerofuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarFkterceroActionPerformed(evt);
            }
        });
        add(botonBuscarFktercerofuncionario);

        jLabel10.setPreferredSize(new java.awt.Dimension(810, 10));
        add(jLabel10);

        jLabelTipopago.setText("FORMA DE PAGO (ESTADO) : ");
        jLabelTipopago.setPreferredSize(new java.awt.Dimension(175, 25));
        add(jLabelTipopago);

        tipopago.setBackground(ClaseGeneral.campo);
        tipopago.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipopago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Fondo Renovable", "Caja Menor", "Anulado" }));
        tipopago.setPreferredSize(new java.awt.Dimension(180, 25));
        add(tipopago);

        jLabel11.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jLabel11);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jSeparator5);

        jLabel12.setText("FECHA ESTIMADA DE PAGO : ");
        jLabel12.setPreferredSize(new java.awt.Dimension(175, 25));
        add(jLabel12);

        fechapago.setFocusable(false);
        fechapago.setMaximumSize(new java.awt.Dimension(120, 25));
        fechapago.setMinimumSize(new java.awt.Dimension(120, 25));
        fechapago.setPreferredSize(new java.awt.Dimension(120, 25));
        add(fechapago);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setEnabled(false);
        jTextField2.setFocusable(false);
        jTextField2.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField2.setOpaque(false);
        jTextField2.setPreferredSize(new java.awt.Dimension(90, 25));
        add(jTextField2);

        jLabelComprobante.setText("NÚMERO DE COMPROBANTE : ");
        jLabelComprobante.setPreferredSize(new java.awt.Dimension(185, 25));
        add(jLabelComprobante);

        comprobante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comprobante.setText("0");
        comprobante.setMargin(new java.awt.Insets(2, 4, 2, 4));
        comprobante.setPreferredSize(new java.awt.Dimension(150, 25));
        comprobante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldFocusGained(evt);
            }
        });
        comprobante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TexyFieldKeyReleased(evt);
            }
        });
        add(comprobante);

        jLabel13.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jLabel13);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator6.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jSeparator6);

        jLabel14.setText("FECHA DEL PAGO (REMBOLSO) : ");
        jLabel14.setPreferredSize(new java.awt.Dimension(195, 25));
        add(jLabel14);

        fechaaplicacion.setFocusable(false);
        fechaaplicacion.setMaximumSize(new java.awt.Dimension(120, 25));
        fechaaplicacion.setMinimumSize(new java.awt.Dimension(120, 25));
        fechaaplicacion.setPreferredSize(new java.awt.Dimension(120, 25));
        add(fechaaplicacion);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.setEnabled(false);
        jTextField3.setFocusable(false);
        jTextField3.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField3.setOpaque(false);
        jTextField3.setPreferredSize(new java.awt.Dimension(90, 25));
        add(jTextField3);

        jLabel15.setPreferredSize(new java.awt.Dimension(810, 10));
        add(jLabel15);

        jPanelObservacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OBSERVACIÓN AL PAGO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        jPanelObservacion.setPreferredSize(new java.awt.Dimension(810, 90));
        jPanelObservacion.setLayout(new java.awt.BorderLayout());

        jScrollObservacion.setPreferredSize(new java.awt.Dimension(430, 70));

        observacion.setBackground(ClaseGeneral.campo);
        observacion.setColumns(20);
        observacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        observacion.setLineWrap(true);
        observacion.setRows(5);
        observacion.setWrapStyleWord(true);
        observacion.setMargin(new java.awt.Insets(2, 5, 2, 5));
        observacion.setPreferredSize(new java.awt.Dimension(430, 70));
        observacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextAreaFocusGained(evt);
            }
        });
        jScrollObservacion.setViewportView(observacion);

        jPanelObservacion.add(jScrollObservacion, java.awt.BorderLayout.CENTER);

        add(jPanelObservacion);

        jLabeL16.setPreferredSize(new java.awt.Dimension(810, 10));
        add(jLabeL16);

        jTabbedPane.setBackground(ClaseGeneral.boton);
        jTabbedPane.setPreferredSize(new java.awt.Dimension(810, 185));

        jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane.setPreferredSize(new java.awt.Dimension(810, 185));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "SOLICITUD", "PROVEEDOR", "VALOR"
            }
        ));
        jTable.setEnabled(false);
        jTable.setFocusable(false);
        jTable.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTable.setRowHeight(20);
        jTable.setSelectionBackground(ClaseGeneral.campo);
        jScrollPane.setViewportView(jTable);

        jTabbedPane.addTab("COMPROBANTES", jScrollPane);

        jScrollPaneSoportesComprobantes.setPreferredSize(new java.awt.Dimension(810, 370));

        jTableSoportesComprobantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CUENTA", "ACTIVIDAD", "SUBGRUPO", "C. COSTOS", "C. INFO", "CUENTA INTERNA", "VALOR"
            }
        ));
        jTableSoportesComprobantes.setEnabled(false);
        jTableSoportesComprobantes.setFocusable(false);
        jTableSoportesComprobantes.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTableSoportesComprobantes.setRowHeight(20);
        jTableSoportesComprobantes.setSelectionBackground(ClaseGeneral.campo);
        jScrollPaneSoportesComprobantes.setViewportView(jTableSoportesComprobantes);

        jTabbedPane.addTab("IMPUTACION", jScrollPaneSoportesComprobantes);

        add(jTabbedPane);

        jTextField16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField16.setEnabled(false);
        jTextField16.setFocusable(false);
        jTextField16.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField16.setOpaque(false);
        jTextField16.setPreferredSize(new java.awt.Dimension(530, 25));
        add(jTextField16);

        jLabel50.setText("Σ SOPORTES : ");
        jLabel50.setPreferredSize(new java.awt.Dimension(100, 25));
        add(jLabel50);

        valorTotal.setBackground(ClaseGeneral.verde);
        valorTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        valorTotal.setForeground(new java.awt.Color(255, 0, 0));
        valorTotal.setText("0");
        valorTotal.setFocusable(false);
        valorTotal.setMargin(new java.awt.Insets(2, 4, 2, 4));
        valorTotal.setPreferredSize(new java.awt.Dimension(170, 25));
        add(valorTotal);
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldFocusGained
        javax.swing.JTextField componente = (javax.swing.JTextField) evt.getComponent();
        componente.selectAll();
        componente.requestFocus();
    }//GEN-LAST:event_TextFieldFocusGained

    private void TexyFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TexyFieldKeyReleased
        try {
            comprobante.setText(ClaseInformacion.formatoEntero.format(Long.parseLong(comprobante.getText().trim().replace(".", ""))));
            valor.setText(ClaseInformacion.formatoDecimal.format(Long.parseLong(valor.getText().trim().replace(".", ""))));
        } catch (Exception ex) {
            Logger.getLogger(PanelPolizas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TexyFieldKeyReleased

    private void TextAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextAreaFocusGained
        javax.swing.JTextArea componente = (javax.swing.JTextArea) evt.getSource();
        componente.selectAll();
        componente.requestFocus();
    }//GEN-LAST:event_TextAreaFocusGained

    private void botonBuscarFkterceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarFkterceroActionPerformed
        javax.swing.JButton componente = (javax.swing.JButton) evt.getSource();
        String eventoFktercero = componente.getName();
        ExternoPanelFktercero panelFktercero = new ExternoPanelFktercero();
        ClaseMensaje.panel(panelFktercero);

        if (eventoFktercero.equals("botonBuscarFktercero")) {
            if (!panelFktercero.fktercero.equals("Seleccione - ")) {
                fktercero.setText(panelFktercero.fktercero);
            }
        } else if (eventoFktercero.equals("botonBuscarFktercerofuncionario")) {
            if (!panelFktercero.fktercero.equals("Seleccione - ")) {
                fktercerofuncionario.setText(panelFktercero.fktercero);
            }
        }
    }//GEN-LAST:event_botonBuscarFkterceroActionPerformed

    public void metodoInsertar() {
        ClaseGeneral.comprobantes = new Comprobantes();
        ClaseGeneral.comprobantes.setId(Integer.parseInt("" + id.getText()));
        ClaseGeneral.comprobantes.setComprobante(Integer.parseInt("" + comprobante.getText()));
        ClaseGeneral.comprobantes.setFechaaplicacion(fechaaplicacion.getDate());
        ClaseGeneral.comprobantes.setFechaelaboracion(fechaelaboracion.getDate());
        ClaseGeneral.comprobantes.setFechapago(fechapago.getDate());
        ClaseGeneral.comprobantes.setFktercero("" + fktercero.getText());
        ClaseGeneral.comprobantes.setFktercerofuncionario("" + fktercerofuncionario.getText());
        ClaseGeneral.comprobantes.setObservacion(observacion.getText().toUpperCase());
        ClaseGeneral.comprobantes.setTipopago("" + tipopago.getSelectedItem());
        ClaseGeneral.comprobantes.setValor(BigDecimal.valueOf(Long.parseLong("" + valor.getText().trim().replace(".", ""))));
        ClaseGeneral.comprobantes.setAno(Integer.parseInt("" + ano.getText()));

        if (ClaseGeneral.controlComprobantes.verify(ClaseGeneral.comprobantes)) {
            try {
                ClaseGeneral.controlComprobantes.create(ClaseGeneral.comprobantes);
            } catch (Exception ex) {
                Logger.getLogger(PanelComprobantes.class.getName()).log(Level.SEVERE, null, ex);
            }

            estado = "nuevo";
        }
    }

    public void metodoConsultar() {
        try {
            id.setText("" + ClaseGeneral.comprobantes.getId());
            comprobante.setText("" + ClaseGeneral.comprobantes.getComprobante());
            fechaaplicacion.setDate(ClaseGeneral.comprobantes.getFechaaplicacion());
            fechaelaboracion.setDate(ClaseGeneral.comprobantes.getFechaelaboracion());
            fechapago.setDate(ClaseGeneral.comprobantes.getFechapago());
            fktercero.setText(ClaseGeneral.comprobantes.getFktercero());
            fktercerofuncionario.setText(ClaseGeneral.comprobantes.getFktercerofuncionario());
            observacion.setText(ClaseGeneral.comprobantes.getObservacion());
            tipopago.setSelectedItem(ClaseGeneral.comprobantes.getTipopago());
            valor.setText("" + ClaseInformacion.formatoDecimal.format(ClaseGeneral.comprobantes.getValor()));
            ano.setText("" + ClaseGeneral.comprobantes.getAno());

            /**/ metodoMostrarSoportesComprobantes();

            /**/ FramePrincipal.metodoEntidadSeleccionada("Pagos Facultad", "Comprobantes *");

            estado = "consultar";
        } catch (Exception ex) {
            Logger.getLogger(PanelResoluciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void metodoActualizar() {
        Comprobantes comprobantesId = ClaseGeneral.comprobantes;
        ClaseGeneral.comprobantes = new Comprobantes();
        ClaseGeneral.comprobantes.setId(Integer.parseInt("" + id.getText()));
        ClaseGeneral.comprobantes.setComprobante(Integer.parseInt("" + comprobante.getText()));
        ClaseGeneral.comprobantes.setFechaaplicacion(fechaaplicacion.getDate());
        ClaseGeneral.comprobantes.setFechaelaboracion(fechaelaboracion.getDate());
        ClaseGeneral.comprobantes.setFechapago(fechapago.getDate());
        ClaseGeneral.comprobantes.setFktercero("" + fktercero.getText());
        ClaseGeneral.comprobantes.setFktercerofuncionario("" + fktercerofuncionario.getText());
        ClaseGeneral.comprobantes.setObservacion(observacion.getText().toUpperCase());
        ClaseGeneral.comprobantes.setTipopago("" + tipopago.getSelectedItem());
        ClaseGeneral.comprobantes.setValor(BigDecimal.valueOf(Long.parseLong("" + valor.getText().trim().replace(".", ""))));
        ClaseGeneral.comprobantes.setAno(Integer.parseInt("" + ano.getText()));

        if (ClaseGeneral.controlComprobantes.verify(ClaseGeneral.comprobantes)) {
            try {
                ClaseGeneral.controlComprobantes.edit(ClaseGeneral.comprobantes, comprobantesId);

                /**/if (tipopago.getSelectedItem().equals("Anulado")) {
                    ClaseGeneral.controlCumplidoscomprobantes.destroyFkcomprobanteAno(ClaseGeneral.comprobantes);
                    ClaseGeneral.controlFacturascomprobantes.destroyFkcomprobanteAno(ClaseGeneral.comprobantes);
                    ClaseGeneral.controlSoportescomprobantes.destroyFkcomprobanteAno(ClaseGeneral.comprobantes);
                }

            } catch (Exception ex) {
                Logger.getLogger(PanelComprobantes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void metodoEliminar() {
        try {
            ClaseGeneral.controlComprobantes.destroy(ClaseGeneral.comprobantes);
            ClaseGeneral.controlCumplidoscomprobantes.destroyFkcomprobanteAno(ClaseGeneral.comprobantes);
            ClaseGeneral.controlFacturascomprobantes.destroyFkcomprobanteAno(ClaseGeneral.comprobantes);
            ClaseGeneral.controlSoportescomprobantes.destroyFkcomprobanteAno(ClaseGeneral.comprobantes);
        } catch (Exception ex) {
            Logger.getLogger(PanelComprobantes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void metodoMostrar(List lista) {//Luego de buscar que muestre la informacion
        ClaseGeneral.comprobantes = new Comprobantes();

        jTable.getColumnModel().getColumn(2).setCellRenderer(informacion.modeloDerecha);

        for (int i = 0; i < 1000; i++) {
            jTable.setValueAt("", i, 0);
            jTable.setValueAt("", i, 1);
            jTable.setValueAt("", i, 2);
        }

        int i = 0;
        for (Object lista1 : lista) {
            ClaseGeneral.comprobantes = (Comprobantes) lista1;
            if (i < 1000) {
                jTable.setValueAt("" + ClaseGeneral.comprobantes.getId(), i, 0);
                jTable.setValueAt("" + ClaseGeneral.comprobantes.getFktercero(), i, 1);
                jTable.setValueAt("" + ClaseInformacion.formatoDecimal.format(ClaseGeneral.comprobantes.getValor()), i, 2);
            }
            i++;
        }

        jTable.clearSelection();
        jTable.getColumnModel().getColumn(0).setPreferredWidth(150);
        jTable.getColumnModel().getColumn(1).setPreferredWidth(510);
        jTable.getColumnModel().getColumn(2).setPreferredWidth(150);
    }
    
    public void metodoMostrar(int ano) {
        ClaseGeneral.comprobantes = new Comprobantes();
        lista = ClaseGeneral.controlComprobantes.findAllInComprobantesByORDERBYAno(ano);

        jTable.getColumnModel().getColumn(2).setCellRenderer(informacion.modeloDerecha);

        for (int i = 0; i < 1000; i++) {
            jTable.setValueAt("", i, 0);
            jTable.setValueAt("", i, 1);
            jTable.setValueAt("", i, 2);
        }

        int i = 0;
        for (Object lista1 : lista) {
            ClaseGeneral.comprobantes = (Comprobantes) lista1;
            if (i < 1000) {
                jTable.setValueAt("" + ClaseGeneral.comprobantes.getId(), i, 0);
                jTable.setValueAt("" + ClaseGeneral.comprobantes.getFktercero(), i, 1);
                jTable.setValueAt("" + ClaseInformacion.formatoDecimal.format(ClaseGeneral.comprobantes.getValor()), i, 2);
            }
            i++;
        }

        jTable.clearSelection();
        jTable.getColumnModel().getColumn(0).setPreferredWidth(150);
        jTable.getColumnModel().getColumn(1).setPreferredWidth(510);
        jTable.getColumnModel().getColumn(2).setPreferredWidth(150);
    }

    public void metodoMostrarSoportesComprobantes() {
        BigDecimal valTotal = BigDecimal.ZERO;
        ClaseGeneral.soportescomprobantes = new Soportescomprobantes();
        lista = ClaseGeneral.controlSoportescomprobantes.findAllInSoportescomprobantesByFkcomprobanteAno(ClaseGeneral.comprobantes.getId(), ClaseGeneral.comprobantes.getAno());

        jTableSoportesComprobantes.getColumnModel().getColumn(6).setCellRenderer(informacion.modeloDerecha);

        for (int i = 0; i < 100; i++) {
            jTableSoportesComprobantes.setValueAt("", i, 0);
            jTableSoportesComprobantes.setValueAt("", i, 1);
            jTableSoportesComprobantes.setValueAt("", i, 2);
            jTableSoportesComprobantes.setValueAt("", i, 3);
            jTableSoportesComprobantes.setValueAt("", i, 4);
            jTableSoportesComprobantes.setValueAt("", i, 5);
            jTableSoportesComprobantes.setValueAt("", i, 6);
        }

        int i = 0;
        for (Object lista1 : lista) {
            ClaseGeneral.soportescomprobantes = (Soportescomprobantes) lista1;
            jTableSoportesComprobantes.setValueAt("" + ClaseGeneral.soportescomprobantes.getCuenta(), i, 0);
            jTableSoportesComprobantes.setValueAt("" + ClaseGeneral.soportescomprobantes.getActividad(), i, 1);
            jTableSoportesComprobantes.setValueAt("" + ClaseGeneral.soportescomprobantes.getSubgrupo(), i, 2);
            jTableSoportesComprobantes.setValueAt("" + ClaseGeneral.soportescomprobantes.getCcostos(), i, 3);
            jTableSoportesComprobantes.setValueAt("" + ClaseGeneral.soportescomprobantes.getCinfo(), i, 4);
            jTableSoportesComprobantes.setValueAt("" + ClaseGeneral.soportescomprobantes.getCuentainterna(), i, 5);
            jTableSoportesComprobantes.setValueAt("" + ClaseInformacion.formatoDecimal.format(ClaseGeneral.soportescomprobantes.getValor()), i, 6);
            valTotal = valTotal.add(ClaseGeneral.soportescomprobantes.getValor());
            i++;
        }

        jTableSoportesComprobantes.clearSelection();
        jTableSoportesComprobantes.getColumnModel().getColumn(0).setPreferredWidth(110);
        jTableSoportesComprobantes.getColumnModel().getColumn(1).setPreferredWidth(110);
        jTableSoportesComprobantes.getColumnModel().getColumn(2).setPreferredWidth(110);
        jTableSoportesComprobantes.getColumnModel().getColumn(3).setPreferredWidth(110);
        jTableSoportesComprobantes.getColumnModel().getColumn(4).setPreferredWidth(110);
        jTableSoportesComprobantes.getColumnModel().getColumn(5).setPreferredWidth(110);
        jTableSoportesComprobantes.getColumnModel().getColumn(6).setPreferredWidth(150);
        valorTotal.setText("" + ClaseInformacion.formatoDecimal.format(valTotal));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ano;
    private javax.swing.JButton botonBuscarFktercero;
    private javax.swing.JButton botonBuscarFktercerofuncionario;
    public javax.swing.JTextField comprobante;
    public org.jdesktop.swingx.JXDatePicker fechaaplicacion;
    public org.jdesktop.swingx.JXDatePicker fechaelaboracion;
    public org.jdesktop.swingx.JXDatePicker fechapago;
    private javax.swing.JTextField fktercero;
    private javax.swing.JTextField fktercerofuncionario;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabeL16;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelComprobante;
    private javax.swing.JLabel jLabelFktercero;
    private javax.swing.JLabel jLabelFktercerofuncionario;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelTipopago;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JPanel jPanelObservacion;
    private javax.swing.JScrollPane jScrollObservacion;
    public javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPaneSoportesComprobantes;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public javax.swing.JTabbedPane jTabbedPane;
    public javax.swing.JTable jTable;
    private javax.swing.JTable jTableSoportesComprobantes;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    public javax.swing.JTextArea observacion;
    private javax.swing.JPanel panelBalanceSoportes;
    private javax.swing.JScrollPane scrollPaneBalanceSoportes;
    private javax.swing.JTextArea textAreaBalanceSoportes;
    private javax.swing.JComboBox tipopago;
    public javax.swing.JTextField valor;
    public javax.swing.JTextField valorTotal;
    // End of variables declaration//GEN-END:variables
}
