/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExternoPanelEntrega.java
 *
 * Created on 27/11/2012, 04:01:30 PM
 */
package frame;

import clases.ClaseGeneral;
import clases.ClaseInformacion;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Jhon Lopez
 */
public class ExternoPanelEntrega extends javax.swing.JPanel {

    /** Creates new form ExternoPanelEntrega */
    public ExternoPanelEntrega() {
        initComponents();

        fecha.setFormats(new SimpleDateFormat("yyyy-MM-dd"));
        fecha.setDate(new Date(ClaseInformacion.calendario.getTimeInMillis()));
    }

    /**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        separador1 = new javax.swing.JSeparator();
        fecha = new org.jdesktop.swingx.JXDatePicker();

        setPreferredSize(new java.awt.Dimension(260, 170));

        jLabel1.setBackground(ClaseGeneral.titulo);
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Entrega de Documentos");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 25));
        add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setPreferredSize(new java.awt.Dimension(250, 10));
        add(jLabel2);

        jLabel3.setText("<html><p align = center>FAVOR ELIJA LA FECHA DE ENTREGA DE<BR />DOCUMENTOS EN LA SECCIÓN DE PRESUPUESTO</p></html>");
        jLabel3.setPreferredSize(new java.awt.Dimension(250, 60));
        add(jLabel3);

        separador1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        separador1.setPreferredSize(new java.awt.Dimension(250, 10));
        add(separador1);

        fecha.setFocusable(false);
        fecha.setMaximumSize(new java.awt.Dimension(120, 25));
        fecha.setMinimumSize(new java.awt.Dimension(120, 25));
        fecha.setPreferredSize(new java.awt.Dimension(120, 25));
        add(fecha);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public org.jdesktop.swingx.JXDatePicker fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator separador1;
    // End of variables declaration//GEN-END:variables
}
