/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import clases.ClaseBaseDatos;
import clases.ClaseGeneral;
import clases.ClaseInformacion;
import clases.ClaseMensaje;
import java.net.UnknownHostException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Usuario
 */
public class FrameInicio extends javax.swing.JFrame {

    private ClaseGeneral general = new ClaseGeneral();
    private ClaseBaseDatos datos = new ClaseBaseDatos();
    private ExternoPanelContrasena panelContrasena = new ExternoPanelContrasena();
    private FramePrincipal frame;
    private boolean booleano;

    /** Creates new form FrameInicio */
    public FrameInicio() {
        initComponents();
        ClaseBaseDatos.conectar();
    }

    /**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        labTitulo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        separador1 = new javax.swing.JSeparator();
        jProgressBar = new javax.swing.JProgressBar();
        separador2 = new javax.swing.JSeparator();
        botonIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setMinimumSize(new java.awt.Dimension(240, 150));

        jPanel.setMaximumSize(new java.awt.Dimension(250, 130));
        jPanel.setMinimumSize(new java.awt.Dimension(250, 130));
        jPanel.setPreferredSize(new java.awt.Dimension(250, 130));

        labTitulo.setBackground(ClaseGeneral.titulo);
        labTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labTitulo.setText("Ingresar");
        labTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        labTitulo.setOpaque(true);
        labTitulo.setPreferredSize(new java.awt.Dimension(250, 24));
        jPanel.add(labTitulo);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setPreferredSize(new java.awt.Dimension(250, 10));
        jPanel.add(jLabel11);

        separador1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        separador1.setPreferredSize(new java.awt.Dimension(250, 10));
        jPanel.add(separador1);

        jProgressBar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jProgressBar.setForeground(ClaseGeneral.boton);
        jProgressBar.setMaximum(18);
        jProgressBar.setMinimum(1);
        jProgressBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBar.setFocusable(false);
        jProgressBar.setMaximumSize(new java.awt.Dimension(220, 25));
        jProgressBar.setMinimumSize(new java.awt.Dimension(220, 25));
        jProgressBar.setPreferredSize(new java.awt.Dimension(250, 25));
        jProgressBar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jProgressBarStateChanged(evt);
            }
        });
        jPanel.add(jProgressBar);

        separador2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        separador2.setPreferredSize(new java.awt.Dimension(250, 10));
        jPanel.add(separador2);

        botonIngresar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonIngresar.setText("Inicio");
        botonIngresar.setFocusable(false);
        botonIngresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonIngresar.setMaximumSize(new java.awt.Dimension(100, 30));
        botonIngresar.setMinimumSize(new java.awt.Dimension(100, 30));
        botonIngresar.setPreferredSize(new java.awt.Dimension(100, 30));
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });
        jPanel.add(botonIngresar);

        getContentPane().add(jPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        try {
            VerPanelContrasena();
        } catch (UnknownHostException ex) {
            Logger.getLogger(FrameInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void jProgressBarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jProgressBarStateChanged
        if (frame.isCargado) {
            VerFramePrincipal();
        }
    }//GEN-LAST:event_jProgressBarStateChanged

    public void VerPanelContrasena() throws UnknownHostException {
        try {
            booleano = true;
            panelContrasena.password.setText("");
            ClaseMensaje.panel(panelContrasena);
            String usuario = panelContrasena.getUsuario();
            String password = panelContrasena.getPassword();

//            if (ClaseInformacion.ObtenerIP().equals("19216813711")
//                    || ClaseInformacion.ObtenerIP().equals("19216823204")) {
//                datos.query("SELECT * FROM TERCEROS WHERE ID = '" + usuario + "' "
//                        + "AND ID = '" + password + "'");
//            } else {
                datos.query("SELECT * FROM TERCEROS, ACCESO WHERE (TERCEROS.ID = '" + usuario + "' "
                        + "AND TERCEROS.ID = '" + password + "' "
                        + "AND IP = '" + ClaseInformacion.ObtenerIP() + "' "
                        + ") OR (ACCESO.ID = '" + usuario + "' "
                        + "AND PASSWORD = '" + password + "' "
                        + "AND TERCEROS.ID = ACCESO.ID)");
//            }

            while (ClaseBaseDatos.resultado.next()) {
                ClaseGeneral.cargando = true;
                ClaseGeneral.perfil = ClaseBaseDatos.resultado.getString("PERFIL");
                ClaseGeneral.dependencia = ClaseBaseDatos.resultado.getString("DEPENDENCIA");
            }
            
            datos.query("SELECT FACULTAD FROM DEPENDENCIA "
                        + "WHERE CODIGO = '" + ClaseGeneral.dependencia + "'");

            while (ClaseBaseDatos.resultado.next()) {
                ClaseGeneral.facultad = ClaseBaseDatos.resultado.getString("FACULTAD");
            }

            if (ClaseGeneral.cargando) {
                botonIngresar.setEnabled(false);
                booleano = false;
                labTitulo.setText("Ingresando");
                frame = new FramePrincipal();
            }

            if (booleano) {
                ClaseMensaje.error("ERROR al intentar iniciar sesión");
                //VerPanelContrasena();
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrameInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void VerFramePrincipal() {
        ClaseGeneral.cargando = false;

        FramePrincipal.setDefaultLookAndFeelDecorated(true);
        frame.setVisible(true);
        frame.pack();
        frame.setSize(1041, 743);
        frame.setLocationRelativeTo(null);
        frame.setResizable(false);
        frame.metodoLimpiar();
        frame.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/iconos16/ICO.png")).getImage());
        this.dispose();
    }

//    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                JFrame.setDefaultLookAndFeelDecorated(true);
                FrameInicio frame = new FrameInicio();
                frame.setVisible(true);
                frame.pack();
                frame.setSize(280, 180);
                frame.setLocationRelativeTo(null);
                frame.setResizable(false);
                frame.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/iconos16/ICO.png")).getImage());
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel;
    public static javax.swing.JProgressBar jProgressBar;
    private javax.swing.JLabel labTitulo;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    // End of variables declaration//GEN-END:variables
}
