/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelCuentas.java
 *
 * Created on 16/01/2012, 05:14:48 PM
 */
package frame;

import clases.ClaseGeneral;
import clases.ClaseInformacion;
import clases.ClaseMensaje;
import entidades.Cuentas;
import entidades.Soportescuentas;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Jhon Lopez
 */
public class PanelCuentas extends javax.swing.JPanel {

    private List lista = new ArrayList();
    private ClaseInformacion informacion = new ClaseInformacion();
    private String estado = "";

    /**
     * Creates new form PanelCuentas
     */
    public PanelCuentas() {
        initComponents();

        fechadigitacion.setFormats(new SimpleDateFormat("yyyy-MM-dd"));
        fechapresupuestal.setFormats(new SimpleDateFormat("yyyy-MM-dd"));
        fechatransaccion.setFormats(new SimpleDateFormat("yyyy-MM-dd"));

        fechadigitacion.setDate(new Date(ClaseInformacion.calendario.getTimeInMillis()));
        fechapresupuestal.setDate(new Date(ClaseInformacion.calendario.getTimeInMillis()));
        fechatransaccion.setDate(new Date(ClaseInformacion.calendario.getTimeInMillis()));

//        metodoMostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDocumento = new javax.swing.JLabel();
        documento = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jLabelSoporte = new javax.swing.JLabel();
        soporte = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        jLabelSoporte1 = new javax.swing.JLabel();
        numeroseguimiento = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        jLabelFktercero = new javax.swing.JLabel();
        fktercero = new javax.swing.JTextField();
        botonBuscarFktercero = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabelIngreso = new javax.swing.JLabel();
        ingreso = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jLabelEgreso = new javax.swing.JLabel();
        egreso = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel81 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        fechadigitacion = new org.jdesktop.swingx.JXDatePicker();
        jLabel79 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel55 = new javax.swing.JLabel();
        fechapresupuestal = new org.jdesktop.swingx.JXDatePicker();
        jTextField15 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        fechatransaccion = new org.jdesktop.swingx.JXDatePicker();
        jTextField14 = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jLabelCuentacontrol = new javax.swing.JLabel();
        cuentacontrol = new javax.swing.JTextField();
        jLabel82 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jLabelFkcontrato = new javax.swing.JLabel();
        fkcontrato = new javax.swing.JTextField();
        botonAyuda = new javax.swing.JButton();
        jTextField16 = new javax.swing.JTextField();
        jLabel85 = new javax.swing.JLabel();
        jPanelDescripcion = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        jLabeL16 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPaneSoportesComprobantes = new javax.swing.JScrollPane();
        jTableSoportesCuentas = new javax.swing.JTable();
        jTextField17 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        valorTotal = new javax.swing.JTextField();

        setName("panelCuentas"); // NOI18N
        setLayout(new java.awt.FlowLayout(0));

        jLabelDocumento.setText("DOCUMENTO : ");
        jLabelDocumento.setPreferredSize(new java.awt.Dimension(95, 25));
        add(jLabelDocumento);

        documento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        documento.setText("0");
        documento.setMargin(new java.awt.Insets(2, 4, 2, 4));
        documento.setPreferredSize(new java.awt.Dimension(140, 25));
        documento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldFocusGained(evt);
            }
        });
        add(documento);

        jLabel73.setPreferredSize(new java.awt.Dimension(10, 25));
        add(jLabel73);

        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator16.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jSeparator16);

        jLabelSoporte.setText("SOPORTE : ");
        jLabelSoporte.setPreferredSize(new java.awt.Dimension(80, 25));
        add(jLabelSoporte);

        soporte.setBackground(ClaseGeneral.campo);
        soporte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        soporte.setText("0");
        soporte.setMargin(new java.awt.Insets(2, 4, 2, 4));
        soporte.setPreferredSize(new java.awt.Dimension(140, 25));
        soporte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldFocusGained(evt);
            }
        });
        add(soporte);

        jLabel74.setPreferredSize(new java.awt.Dimension(10, 25));
        add(jLabel74);

        jSeparator20.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator20.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jSeparator20);

        jLabelSoporte1.setText("# SEGUIMIENTO : ");
        jLabelSoporte1.setPreferredSize(new java.awt.Dimension(110, 25));
        add(jLabelSoporte1);

        numeroseguimiento.setBackground(ClaseGeneral.campo);
        numeroseguimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numeroseguimiento.setText("0");
        numeroseguimiento.setMargin(new java.awt.Insets(2, 4, 2, 4));
        numeroseguimiento.setPreferredSize(new java.awt.Dimension(140, 25));
        numeroseguimiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numeroseguimientoTextFieldFocusGained(evt);
            }
        });
        add(numeroseguimiento);

        jLabel78.setPreferredSize(new java.awt.Dimension(810, 15));
        add(jLabel78);

        jLabelFktercero.setText("CÉDULA DEL PROVEEDOR : ");
        jLabelFktercero.setPreferredSize(new java.awt.Dimension(170, 25));
        add(jLabelFktercero);

        fktercero.setBackground(ClaseGeneral.campo);
        fktercero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fktercero.setFocusable(false);
        fktercero.setMargin(new java.awt.Insets(2, 4, 2, 4));
        fktercero.setPreferredSize(new java.awt.Dimension(585, 25));
        add(fktercero);

        botonBuscarFktercero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos24/search.png"))); // NOI18N
        botonBuscarFktercero.setFocusable(false);
        botonBuscarFktercero.setName("botonBuscarFktercero"); // NOI18N
        botonBuscarFktercero.setPreferredSize(new java.awt.Dimension(25, 24));
        botonBuscarFktercero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarFkterceroActionPerformed(evt);
            }
        });
        add(botonBuscarFktercero);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setEnabled(false);
        jTextField1.setFocusable(false);
        jTextField1.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField1.setOpaque(false);
        jTextField1.setPreferredSize(new java.awt.Dimension(15, 25));
        add(jTextField1);

        jLabelIngreso.setText("VALOR INGRESO : ");
        jLabelIngreso.setPreferredSize(new java.awt.Dimension(125, 25));
        add(jLabelIngreso);

        ingreso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ingreso.setText("0");
        ingreso.setMargin(new java.awt.Insets(2, 4, 2, 4));
        ingreso.setPreferredSize(new java.awt.Dimension(150, 25));
        ingreso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldFocusGained(evt);
            }
        });
        ingreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TexyFieldKeyReleased(evt);
            }
        });
        add(ingreso);

        jLabel80.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jLabel80);

        jSeparator18.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator18.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jSeparator18);

        jLabelEgreso.setText("VALOR EGRESO : ");
        jLabelEgreso.setPreferredSize(new java.awt.Dimension(120, 25));
        add(jLabelEgreso);

        egreso.setBackground(ClaseGeneral.campo);
        egreso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        egreso.setText("0");
        egreso.setMargin(new java.awt.Insets(2, 4, 2, 4));
        egreso.setPreferredSize(new java.awt.Dimension(150, 25));
        egreso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldFocusGained(evt);
            }
        });
        egreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TexyFieldKeyReleased(evt);
            }
        });
        add(egreso);

        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField12.setEnabled(false);
        jTextField12.setFocusable(false);
        jTextField12.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField12.setOpaque(false);
        jTextField12.setPreferredSize(new java.awt.Dimension(195, 25));
        add(jTextField12);

        jLabel81.setPreferredSize(new java.awt.Dimension(810, 15));
        add(jLabel81);

        jLabel50.setText("FECHA DE DIGITACIÓN : ");
        jLabel50.setPreferredSize(new java.awt.Dimension(155, 25));
        add(jLabel50);

        fechadigitacion.setFocusable(false);
        fechadigitacion.setMaximumSize(new java.awt.Dimension(120, 25));
        fechadigitacion.setMinimumSize(new java.awt.Dimension(120, 25));
        fechadigitacion.setPreferredSize(new java.awt.Dimension(120, 25));
        add(fechadigitacion);

        jLabel79.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jLabel79);

        jSeparator17.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator17.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jSeparator17);

        jLabel55.setText("FECHA PRESUPUESTAL : ");
        jLabel55.setPreferredSize(new java.awt.Dimension(150, 25));
        add(jLabel55);

        fechapresupuestal.setFocusable(false);
        fechapresupuestal.setMaximumSize(new java.awt.Dimension(120, 25));
        fechapresupuestal.setMinimumSize(new java.awt.Dimension(120, 25));
        fechapresupuestal.setPreferredSize(new java.awt.Dimension(120, 25));
        add(fechapresupuestal);

        jTextField15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField15.setEnabled(false);
        jTextField15.setFocusable(false);
        jTextField15.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField15.setOpaque(false);
        jTextField15.setPreferredSize(new java.awt.Dimension(195, 25));
        add(jTextField15);

        jLabel51.setText("FECHA DE TRANSACCIÓN : ");
        jLabel51.setPreferredSize(new java.awt.Dimension(165, 25));
        add(jLabel51);

        fechatransaccion.setFocusable(false);
        fechatransaccion.setMaximumSize(new java.awt.Dimension(120, 25));
        fechatransaccion.setMinimumSize(new java.awt.Dimension(120, 25));
        fechatransaccion.setPreferredSize(new java.awt.Dimension(120, 25));
        add(fechatransaccion);

        jTextField14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField14.setEnabled(false);
        jTextField14.setFocusable(false);
        jTextField14.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField14.setOpaque(false);
        jTextField14.setPreferredSize(new java.awt.Dimension(515, 25));
        add(jTextField14);

        jLabel71.setPreferredSize(new java.awt.Dimension(810, 15));
        add(jLabel71);

        jLabelCuentacontrol.setText("CUENTA CONTROL : ");
        jLabelCuentacontrol.setPreferredSize(new java.awt.Dimension(130, 25));
        add(jLabelCuentacontrol);

        cuentacontrol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cuentacontrol.setText("0");
        cuentacontrol.setMargin(new java.awt.Insets(2, 4, 2, 4));
        cuentacontrol.setPreferredSize(new java.awt.Dimension(150, 25));
        cuentacontrol.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldFocusGained(evt);
            }
        });
        add(cuentacontrol);

        jLabel82.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jLabel82);

        jSeparator19.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator19.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jSeparator19);

        jLabelFkcontrato.setText("CONTRATO : ");
        jLabelFkcontrato.setPreferredSize(new java.awt.Dimension(90, 25));
        add(jLabelFkcontrato);

        fkcontrato.setBackground(ClaseGeneral.campo);
        fkcontrato.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fkcontrato.setText("0");
        fkcontrato.setMargin(new java.awt.Insets(2, 4, 2, 4));
        fkcontrato.setPreferredSize(new java.awt.Dimension(300, 25));
        fkcontrato.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldFocusGained(evt);
            }
        });
        add(fkcontrato);

        botonAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos24/info.png"))); // NOI18N
        botonAyuda.setFocusable(false);
        botonAyuda.setPreferredSize(new java.awt.Dimension(25, 24));
        botonAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAyudaActionPerformed(evt);
            }
        });
        add(botonAyuda);

        jTextField16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField16.setEnabled(false);
        jTextField16.setFocusable(false);
        jTextField16.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField16.setOpaque(false);
        jTextField16.setPreferredSize(new java.awt.Dimension(40, 25));
        add(jTextField16);

        jLabel85.setPreferredSize(new java.awt.Dimension(810, 15));
        add(jLabel85);

        jPanelDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DESCRIPCION DEL PAGO", 0, 0, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        jPanelDescripcion.setPreferredSize(new java.awt.Dimension(810, 120));
        jPanelDescripcion.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setPreferredSize(new java.awt.Dimension(430, 70));

        descripcion.setBackground(ClaseGeneral.campo);
        descripcion.setColumns(20);
        descripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descripcion.setLineWrap(true);
        descripcion.setRows(5);
        descripcion.setWrapStyleWord(true);
        descripcion.setMargin(new java.awt.Insets(2, 5, 2, 5));
        descripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextAreaFocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(descripcion);

        jPanelDescripcion.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanelDescripcion);

        jLabeL16.setPreferredSize(new java.awt.Dimension(810, 10));
        add(jLabeL16);

        jTabbedPane1.setBackground(ClaseGeneral.boton);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(810, 135));

        jScrollPaneSoportesComprobantes.setPreferredSize(new java.awt.Dimension(800, 135));

        jTableSoportesCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CUENTA", "ACTIVIDAD", "SUBGRUPO", "C. INGRESO", "C. COSTOS", "C. INFO", "CUENTA INTERNA", "VALOR"
            }
        ));
        jTableSoportesCuentas.setEnabled(false);
        jTableSoportesCuentas.setFocusable(false);
        jTableSoportesCuentas.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTableSoportesCuentas.setRowHeight(20);
        jTableSoportesCuentas.setSelectionBackground(ClaseGeneral.campo);
        jScrollPaneSoportesComprobantes.setViewportView(jTableSoportesCuentas);

        jTabbedPane1.addTab("IMPUTACION", jScrollPaneSoportesComprobantes);

        add(jTabbedPane1);

        jTextField17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField17.setEnabled(false);
        jTextField17.setFocusable(false);
        jTextField17.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField17.setOpaque(false);
        jTextField17.setPreferredSize(new java.awt.Dimension(530, 25));
        add(jTextField17);

        jLabel52.setText("Σ SOPORTES : ");
        jLabel52.setPreferredSize(new java.awt.Dimension(100, 25));
        add(jLabel52);

        valorTotal.setBackground(ClaseGeneral.verde);
        valorTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        valorTotal.setForeground(new java.awt.Color(255, 0, 0));
        valorTotal.setText("0");
        valorTotal.setFocusable(false);
        valorTotal.setMargin(new java.awt.Insets(2, 4, 2, 4));
        valorTotal.setPreferredSize(new java.awt.Dimension(170, 25));
        add(valorTotal);
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldFocusGained
        javax.swing.JTextField componente = (javax.swing.JTextField) evt.getComponent();
        componente.selectAll();
        componente.requestFocus();
    }//GEN-LAST:event_TextFieldFocusGained
 
    private void TextAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextAreaFocusGained
        javax.swing.JTextArea componente = (javax.swing.JTextArea) evt.getComponent();
        componente.selectAll();
        componente.requestFocus();
    }//GEN-LAST:event_TextAreaFocusGained

    private void botonBuscarFkterceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarFkterceroActionPerformed
        javax.swing.JButton componente = (javax.swing.JButton) evt.getSource();
        String eventoFktercero = componente.getName();
        ExternoPanelFktercero panelFktercero = new ExternoPanelFktercero();
        ClaseMensaje.panel(panelFktercero);

        if (eventoFktercero.equals("botonBuscarFktercero")) {
            if (!panelFktercero.fktercero.equals("Seleccione - ")) {
                fktercero.setText(panelFktercero.fktercero);
            }
        }
    }//GEN-LAST:event_botonBuscarFkterceroActionPerformed

    private void botonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAyudaActionPerformed
        ClaseMensaje.informacion("<html><body>"
                + "Ingrese el numero del contrato, ejemplo :<br/>"
                + "<ul>"
                + "  <li>Si es un contrato corporativo : <b>033-2012</b></li>"
                + "  <li>Si es un contrato de la dependencia : <b>FCNE-D-001-14</b> o <b>0090.0090_018.018-001-14</li>"
                + "  <li>Si no posee contrato : <b>N/A</b></li>"
                + "</ul>"
                + "</body></html>");
    }//GEN-LAST:event_botonAyudaActionPerformed

    private void TexyFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TexyFieldKeyReleased
        try {
            egreso.setText(ClaseInformacion.formatoDecimal.format(Long.parseLong(egreso.getText().trim().replace(".", ""))));
            ingreso.setText(ClaseInformacion.formatoDecimal.format(Long.parseLong(ingreso.getText().trim().replace(".", ""))));
        } catch (Exception ex) {
            Logger.getLogger(PanelPolizas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TexyFieldKeyReleased

    private void numeroseguimientoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroseguimientoTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroseguimientoTextFieldFocusGained

    public void metodoInsertar() {
        ClaseGeneral.cuentas = new Cuentas();
        ClaseGeneral.cuentas.setDocumento(documento.getText());
        ClaseGeneral.cuentas.setCuentacontrol(cuentacontrol.getText());
        ClaseGeneral.cuentas.setDescripcion(descripcion.getText().toUpperCase());
        ClaseGeneral.cuentas.setEgreso(BigDecimal.valueOf(Long.parseLong("" + egreso.getText().trim().replace(".", ""))));
        ClaseGeneral.cuentas.setFechadigitacion(fechadigitacion.getDate());
        ClaseGeneral.cuentas.setFechapresupuestal(fechapresupuestal.getDate());
        ClaseGeneral.cuentas.setFechatransaccion(fechatransaccion.getDate());
        ClaseGeneral.cuentas.setFktercero("" + fktercero.getText());
        ClaseGeneral.cuentas.setIngreso(BigDecimal.valueOf(Long.parseLong("" + ingreso.getText().trim().replace(".", ""))));
        ClaseGeneral.cuentas.setSoporte(soporte.getText());
        ClaseGeneral.cuentas.setFkcontrato(fkcontrato.getText());
        ClaseGeneral.cuentas.setNumeroseguimiento(numeroseguimiento.getText());

        if (ClaseGeneral.controlCuentas.verify(ClaseGeneral.cuentas)) {
            try {
                ClaseGeneral.controlCuentas.create(ClaseGeneral.cuentas);

            } catch (Exception ex) {
                Logger.getLogger(PanelCuentas.class.getName()).log(Level.SEVERE, null, ex);
            }

            estado = "nuevo";
        }
    }

    public void metodoConsultar() {
        try {
            documento.setText(ClaseGeneral.cuentas.getDocumento());
            cuentacontrol.setText(ClaseGeneral.cuentas.getCuentacontrol());
            descripcion.setText(ClaseGeneral.cuentas.getDescripcion());
            egreso.setText("" + ClaseInformacion.formatoDecimal.format(ClaseGeneral.cuentas.getEgreso()));
            fechadigitacion.setDate(ClaseGeneral.cuentas.getFechadigitacion());
            fechapresupuestal.setDate(ClaseGeneral.cuentas.getFechapresupuestal());
            fechatransaccion.setDate(ClaseGeneral.cuentas.getFechatransaccion());
            fktercero.setText(ClaseGeneral.cuentas.getFktercero());
            ingreso.setText("" + ClaseInformacion.formatoDecimal.format(ClaseGeneral.cuentas.getIngreso()));
            soporte.setText(ClaseGeneral.cuentas.getSoporte());
            fkcontrato.setText(ClaseGeneral.cuentas.getFkcontrato());
            numeroseguimiento.setText(ClaseGeneral.cuentas.getNumeroseguimiento());
            
            /**/ metodoMostrarSoportesCuentas();
            
            /**/ FramePrincipal.metodoEntidadSeleccionada("Gastos Facultad", "Cuentas *");

            estado = "consultar";
        } catch (Exception ex) {
            Logger.getLogger(PanelResoluciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void metodoActualizar() {
        Cuentas cuentasId = ClaseGeneral.cuentas;

        ClaseGeneral.cuentas = new Cuentas();
        ClaseGeneral.cuentas.setDocumento(documento.getText());
        ClaseGeneral.cuentas.setCuentacontrol(cuentacontrol.getText());
        ClaseGeneral.cuentas.setDescripcion(descripcion.getText().toUpperCase());
        ClaseGeneral.cuentas.setEgreso(BigDecimal.valueOf(Long.parseLong("" + egreso.getText().trim().replace(".", ""))));
        ClaseGeneral.cuentas.setFechadigitacion(fechadigitacion.getDate());
        ClaseGeneral.cuentas.setFechapresupuestal(fechapresupuestal.getDate());
        ClaseGeneral.cuentas.setFechatransaccion(fechatransaccion.getDate());
        ClaseGeneral.cuentas.setFktercero("" + fktercero.getText());
        ClaseGeneral.cuentas.setIngreso(BigDecimal.valueOf(Long.parseLong("" + ingreso.getText().trim().replace(".", ""))));
        ClaseGeneral.cuentas.setSoporte(soporte.getText());
        ClaseGeneral.cuentas.setFkcontrato(fkcontrato.getText());
        ClaseGeneral.cuentas.setNumeroseguimiento(numeroseguimiento.getText());

        if (ClaseGeneral.controlCuentas.verify(ClaseGeneral.cuentas)) {
            try {
                ClaseGeneral.controlCuentas.edit(ClaseGeneral.cuentas, cuentasId);
                ClaseGeneral.controlObservacionescuentas.editFkcuenta(soporte.getText(), cuentasId.getSoporte());
                ClaseGeneral.controlSoportescuentas.editFkcuenta(soporte.getText(), cuentasId.getSoporte());
            } catch (Exception ex) {
                Logger.getLogger(PanelCuentas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void metodoEliminar() {
        try {
            ClaseGeneral.controlCuentas.destroy(soporte.getText());
            ClaseGeneral.controlObservacionescuentas.destroyFkcuenta(soporte.getText());
            ClaseGeneral.controlSoportescuentas.destroyFkcuenta(soporte.getText());

        } catch (Exception ex) {
            Logger.getLogger(PanelCuentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void metodoMostrarSoportesCuentas() {
        BigDecimal valTotal = BigDecimal.ZERO;
        ClaseGeneral.soportescuentas = new Soportescuentas();
        lista = ClaseGeneral.controlSoportescuentas.findAllInSoportescuentasByFkcuenta(ClaseGeneral.cuentas.getSoporte());

        jTableSoportesCuentas.getColumnModel().getColumn(7).setCellRenderer(informacion.modeloDerecha);

        for (int i = 0; i < 100; i++) {
            jTableSoportesCuentas.setValueAt("", i, 0);
            jTableSoportesCuentas.setValueAt("", i, 1);
            jTableSoportesCuentas.setValueAt("", i, 2);
            jTableSoportesCuentas.setValueAt("", i, 3);
            jTableSoportesCuentas.setValueAt("", i, 4);
            jTableSoportesCuentas.setValueAt("", i, 5);
            jTableSoportesCuentas.setValueAt("", i, 6);
            jTableSoportesCuentas.setValueAt("", i, 7);
        }

        int i = 0;
        for (Object lista1 : lista) {
            ClaseGeneral.soportescuentas = (Soportescuentas) lista1;
            jTableSoportesCuentas.setValueAt("" + ClaseGeneral.soportescuentas.getCuenta(), i, 0);
            jTableSoportesCuentas.setValueAt("" + ClaseGeneral.soportescuentas.getActividad(), i, 1);
            jTableSoportesCuentas.setValueAt("" + ClaseGeneral.soportescuentas.getSubgrupo(), i, 2);
            jTableSoportesCuentas.setValueAt("" + ClaseGeneral.soportescuentas.getCingreso(), i, 3);
            jTableSoportesCuentas.setValueAt("" + ClaseGeneral.soportescuentas.getCcostos(), i, 4);
            jTableSoportesCuentas.setValueAt("" + ClaseGeneral.soportescuentas.getCinfo(), i, 5);
            jTableSoportesCuentas.setValueAt("" + ClaseGeneral.soportescuentas.getCuentainterna(), i, 6);
            jTableSoportesCuentas.setValueAt("" + ClaseInformacion.formatoDecimal.format(ClaseGeneral.soportescuentas.getValor()), i, 7);
            valTotal = valTotal.add(ClaseGeneral.soportescuentas.getValor());
            i++;
        }
        
        jTableSoportesCuentas.clearSelection();
        jTableSoportesCuentas.getColumnModel().getColumn(0).setPreferredWidth(90);
        jTableSoportesCuentas.getColumnModel().getColumn(1).setPreferredWidth(90);
        jTableSoportesCuentas.getColumnModel().getColumn(2).setPreferredWidth(90);
        jTableSoportesCuentas.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTableSoportesCuentas.getColumnModel().getColumn(4).setPreferredWidth(90);
        jTableSoportesCuentas.getColumnModel().getColumn(5).setPreferredWidth(90);
        jTableSoportesCuentas.getColumnModel().getColumn(6).setPreferredWidth(125);
        jTableSoportesCuentas.getColumnModel().getColumn(7).setPreferredWidth(145);
        valorTotal.setText("" + ClaseInformacion.formatoDecimal.format(valTotal));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAyuda;
    private javax.swing.JButton botonBuscarFktercero;
    public javax.swing.JTextField cuentacontrol;
    private javax.swing.JTextArea descripcion;
    public javax.swing.JTextField documento;
    private javax.swing.JTextField egreso;
    public org.jdesktop.swingx.JXDatePicker fechadigitacion;
    public org.jdesktop.swingx.JXDatePicker fechapresupuestal;
    public org.jdesktop.swingx.JXDatePicker fechatransaccion;
    private javax.swing.JTextField fkcontrato;
    private javax.swing.JTextField fktercero;
    public javax.swing.JTextField ingreso;
    private javax.swing.JLabel jLabeL16;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabelCuentacontrol;
    private javax.swing.JLabel jLabelDocumento;
    private javax.swing.JLabel jLabelEgreso;
    private javax.swing.JLabel jLabelFkcontrato;
    private javax.swing.JLabel jLabelFktercero;
    private javax.swing.JLabel jLabelIngreso;
    private javax.swing.JLabel jLabelSoporte;
    private javax.swing.JLabel jLabelSoporte1;
    private javax.swing.JPanel jPanelDescripcion;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneSoportesComprobantes;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableSoportesCuentas;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField numeroseguimiento;
    private javax.swing.JTextField soporte;
    private javax.swing.JTextField valorTotal;
    // End of variables declaration//GEN-END:variables
}
