/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * PanelSoportescomprobantesContratos.java
 *
 * Created on 16/01/2012, 05:14:48 PM
 */
package frame;

import clases.ClaseGeneral;
import clases.ClaseInformacion;
import clases.ClaseMensaje;
import entidades.Soportesresoluciones;
import entidades.SoportesresolucionesPK;
import entidades.Tercerosresoluciones;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author Jhon Lopez
 */
public class PanelTercerosresoluciones extends javax.swing.JPanel {

    private List lista = new ArrayList();
    private List lista2 = new ArrayList();
    private ClaseInformacion informacion = new ClaseInformacion();
    private BigDecimal salario = BigDecimal.ZERO;
    private double diario = 0.0;
    private List listaSoporte = new ArrayList();
    private String fksoportecuenta;
    private int fksoportecuentaid;
    private int fksoportecomprobante;
    private int fksoportecomprobanteid;
    private int fksoportecomprobanteano;

    /**
     * Creates new form PanelSoportescomprobantesContratos
     */
    public PanelTercerosresoluciones() {
        initComponents();

        cuenta.setFocusable(false);
        actividad.setFocusable(false);
        subgrupo.setFocusable(false);
        ccostos.setFocusable(false);
        cinfo.setFocusable(false);
        cuentainterna.setFocusable(false);

        fkresolucion.setText("" + ClaseGeneral.resoluciones.getResolucionPK().getId());
        objetivo.setText(ClaseGeneral.resoluciones.getObservacion());
        metodoMostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fkcuenta = new javax.swing.JTextField();
        fkcomprobante = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fkresolucion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelTarifa = new javax.swing.JLabel();
        tarifa = new javax.swing.JComboBox();
        botonAyuda1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTabbedPane = new javax.swing.JTabbedPane();
        panelTercero = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonAyuda2 = new javax.swing.JButton();
        fktercero = new javax.swing.JTextField();
        botonBuscarFktercero = new javax.swing.JButton();
        valor = new javax.swing.JTextField();
        botonCALCValor = new javax.swing.JButton();
        textInformacionTercero = new javax.swing.JTextField();
        botonCambiar = new javax.swing.JButton();
        valorTotal = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanelOtraFormaPago = new javax.swing.JPanel();
        jScrollPaneDestino1 = new javax.swing.JScrollPane();
        soporte = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jPanelDestino = new javax.swing.JPanel();
        jScrollPaneDestino = new javax.swing.JScrollPane();
        destino = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jPanelObjetivo = new javax.swing.JPanel();
        jScrollPaneObjetivo = new javax.swing.JScrollPane();
        objetivo = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        panelSoportesresoluciones = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        botonSeleccionarImputacion = new javax.swing.JButton();
        jLabel75 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jTextField4 = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cuenta = new javax.swing.JTextField();
        actividad = new javax.swing.JTextField();
        subgrupo = new javax.swing.JComboBox();
        ccostos = new javax.swing.JTextField();
        cinfo = new javax.swing.JComboBox();
        cuentainterna = new javax.swing.JComboBox();
        valorSoporte = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableImputacion = new javax.swing.JTable();

        fkcuenta.setBackground(ClaseGeneral.campo);
        fkcuenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fkcuenta.setText("-");
        fkcuenta.setMargin(new java.awt.Insets(2, 4, 2, 4));
        fkcuenta.setPreferredSize(new java.awt.Dimension(210, 25));

        fkcomprobante.setBackground(ClaseGeneral.campo);
        fkcomprobante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fkcomprobante.setText("-");
        fkcomprobante.setMargin(new java.awt.Insets(2, 4, 2, 4));
        fkcomprobante.setPreferredSize(new java.awt.Dimension(210, 25));

        id.setBackground(ClaseGeneral.campo);
        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id.setText("-");
        id.setMargin(new java.awt.Insets(2, 4, 2, 4));
        id.setPreferredSize(new java.awt.Dimension(210, 25));

        setName("panelTercerosresolucion"); // NOI18N

        jLabel1.setText("NÚMERO RESOLUCION : ");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 25));
        add(jLabel1);

        fkresolucion.setBackground(ClaseGeneral.verde);
        fkresolucion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fkresolucion.setForeground(ClaseGeneral.rojo);
        fkresolucion.setFocusable(false);
        fkresolucion.setMargin(new java.awt.Insets(2, 4, 2, 4));
        fkresolucion.setPreferredSize(new java.awt.Dimension(150, 25));
        add(fkresolucion);

        jLabel2.setPreferredSize(new java.awt.Dimension(10, 25));
        add(jLabel2);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(10, 25));
        add(jSeparator1);

        jLabelTarifa.setText("TARIFA : ");
        jLabelTarifa.setPreferredSize(new java.awt.Dimension(60, 25));
        add(jLabelTarifa);

        tarifa.setBackground(ClaseGeneral.campo);
        tarifa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tarifa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "PLENA", "REDUCIDA", "ESPECIAL" }));
        tarifa.setPreferredSize(new java.awt.Dimension(130, 25));
        tarifa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxItemStateChanged(evt);
            }
        });
        add(tarifa);

        botonAyuda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos24/info.png"))); // NOI18N
        botonAyuda1.setFocusable(false);
        botonAyuda1.setPreferredSize(new java.awt.Dimension(25, 24));
        botonAyuda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAyuda1ActionPerformed(evt);
            }
        });
        add(botonAyuda1);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.setEnabled(false);
        jTextField3.setFocusable(false);
        jTextField3.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField3.setOpaque(false);
        jTextField3.setPreferredSize(new java.awt.Dimension(240, 25));
        add(jTextField3);

        jTabbedPane.setBackground(ClaseGeneral.campo);
        jTabbedPane.setMinimumSize(new java.awt.Dimension(5657, 110));
        jTabbedPane.setOpaque(true);
        jTabbedPane.setPreferredSize(new java.awt.Dimension(810, 600));

        panelTercero.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelTercero.setPreferredSize(new java.awt.Dimension(800, 99));
        panelTercero.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TERCERO");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel5.setPreferredSize(new java.awt.Dimension(620, 25));
        panelTercero.add(jLabel5);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("VALOR");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel6.setPreferredSize(new java.awt.Dimension(130, 25));
        panelTercero.add(jLabel6);

        botonAyuda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos24/info.png"))); // NOI18N
        botonAyuda2.setFocusable(false);
        botonAyuda2.setPreferredSize(new java.awt.Dimension(25, 24));
        botonAyuda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAyuda2ActionPerformed(evt);
            }
        });
        panelTercero.add(botonAyuda2);

        fktercero.setBackground(ClaseGeneral.campo);
        fktercero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fktercero.setFocusable(false);
        fktercero.setMargin(new java.awt.Insets(2, 4, 2, 4));
        fktercero.setPreferredSize(new java.awt.Dimension(590, 25));
        panelTercero.add(fktercero);

        botonBuscarFktercero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos24/search.png"))); // NOI18N
        botonBuscarFktercero.setFocusable(false);
        botonBuscarFktercero.setName("botonBuscarFktercero"); // NOI18N
        botonBuscarFktercero.setPreferredSize(new java.awt.Dimension(25, 24));
        botonBuscarFktercero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarFkterceroActionPerformed(evt);
            }
        });
        panelTercero.add(botonBuscarFktercero);

        valor.setBackground(ClaseGeneral.campo);
        valor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valor.setText("0");
        valor.setMargin(new java.awt.Insets(2, 4, 2, 4));
        valor.setPreferredSize(new java.awt.Dimension(130, 25));
        valor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldFocusGained(evt);
            }
        });
        valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldKeyReleased(evt);
            }
        });
        panelTercero.add(valor);

        botonCALCValor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos24/process.png"))); // NOI18N
        botonCALCValor.setFocusable(false);
        botonCALCValor.setPreferredSize(new java.awt.Dimension(25, 24));
        botonCALCValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCALCValorActionPerformed(evt);
            }
        });
        panelTercero.add(botonCALCValor);

        textInformacionTercero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textInformacionTercero.setForeground(new java.awt.Color(0, 102, 51));
        textInformacionTercero.setFocusable(false);
        textInformacionTercero.setMargin(new java.awt.Insets(2, 4, 2, 4));
        textInformacionTercero.setOpaque(false);
        textInformacionTercero.setPreferredSize(new java.awt.Dimension(455, 25));
        panelTercero.add(textInformacionTercero);

        botonCambiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos24/process.png"))); // NOI18N
        botonCambiar.setText("Cambiar Salario");
        botonCambiar.setFocusable(false);
        botonCambiar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonCambiar.setPreferredSize(new java.awt.Dimension(160, 24));
        botonCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarActionPerformed(evt);
            }
        });
        panelTercero.add(botonCambiar);

        valorTotal.setBackground(ClaseGeneral.verde);
        valorTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        valorTotal.setForeground(new java.awt.Color(255, 0, 0));
        valorTotal.setText("0");
        valorTotal.setMargin(new java.awt.Insets(2, 4, 2, 4));
        valorTotal.setPreferredSize(new java.awt.Dimension(160, 25));
        panelTercero.add(valorTotal);

        jLabel19.setPreferredSize(new java.awt.Dimension(790, 5));
        panelTercero.add(jLabel19);

        jPanelOtraFormaPago.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OTRA FORMA DE PAGO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        jPanelOtraFormaPago.setPreferredSize(new java.awt.Dimension(790, 75));
        jPanelOtraFormaPago.setLayout(new java.awt.BorderLayout());

        jScrollPaneDestino1.setPreferredSize(new java.awt.Dimension(430, 70));

        soporte.setBackground(ClaseGeneral.campo);
        soporte.setColumns(20);
        soporte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        soporte.setLineWrap(true);
        soporte.setRows(15);
        soporte.setWrapStyleWord(true);
        soporte.setMargin(new java.awt.Insets(2, 5, 2, 5));
        soporte.setPreferredSize(new java.awt.Dimension(250, 300));
        jScrollPaneDestino1.setViewportView(soporte);

        jPanelOtraFormaPago.add(jScrollPaneDestino1, java.awt.BorderLayout.CENTER);

        panelTercero.add(jPanelOtraFormaPago);
        jPanelOtraFormaPago.getAccessibleContext().setAccessibleName("");

        jLabel20.setPreferredSize(new java.awt.Dimension(790, 5));
        panelTercero.add(jLabel20);

        jPanelDestino.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DESTINO (RUTA)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        jPanelDestino.setPreferredSize(new java.awt.Dimension(790, 75));
        jPanelDestino.setLayout(new java.awt.BorderLayout());

        jScrollPaneDestino.setPreferredSize(new java.awt.Dimension(430, 70));

        destino.setBackground(ClaseGeneral.campo);
        destino.setColumns(20);
        destino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        destino.setLineWrap(true);
        destino.setRows(15);
        destino.setWrapStyleWord(true);
        destino.setMargin(new java.awt.Insets(2, 5, 2, 5));
        destino.setPreferredSize(new java.awt.Dimension(250, 300));
        jScrollPaneDestino.setViewportView(destino);

        jPanelDestino.add(jScrollPaneDestino, java.awt.BorderLayout.CENTER);

        panelTercero.add(jPanelDestino);

        jLabel13.setPreferredSize(new java.awt.Dimension(790, 5));
        panelTercero.add(jLabel13);

        jPanelObjetivo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OBJETIVO (PERIODO, COMISION, VALOR GASTOS, VALOR TRANSPORTE)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        jPanelObjetivo.setPreferredSize(new java.awt.Dimension(790, 75));
        jPanelObjetivo.setLayout(new java.awt.BorderLayout());

        jScrollPaneObjetivo.setPreferredSize(new java.awt.Dimension(430, 70));

        objetivo.setBackground(ClaseGeneral.campo);
        objetivo.setColumns(20);
        objetivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        objetivo.setLineWrap(true);
        objetivo.setRows(15);
        objetivo.setWrapStyleWord(true);
        objetivo.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jScrollPaneObjetivo.setViewportView(objetivo);

        jPanelObjetivo.add(jScrollPaneObjetivo, java.awt.BorderLayout.CENTER);

        panelTercero.add(jPanelObjetivo);

        jLabel10.setPreferredSize(new java.awt.Dimension(790, 5));
        panelTercero.add(jLabel10);

        jScrollPane.setPreferredSize(new java.awt.Dimension(790, 125));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "TERCERO", "VALOR"
            }
        ));
        jTable.setEnabled(false);
        jTable.setFocusable(false);
        jTable.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTable.setRowHeight(20);
        jTable.setSelectionBackground(ClaseGeneral.campo);
        jScrollPane.setViewportView(jTable);

        panelTercero.add(jScrollPane);

        jLabel18.setPreferredSize(new java.awt.Dimension(790, 5));
        panelTercero.add(jLabel18);

        jTabbedPane.addTab("TERCERO", panelTercero);

        panelSoportesresoluciones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel73.setPreferredSize(new java.awt.Dimension(790, 15));
        panelSoportesresoluciones.add(jLabel73);

        botonSeleccionarImputacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos24/search.png"))); // NOI18N
        botonSeleccionarImputacion.setText("Seleccionar Imputación");
        botonSeleccionarImputacion.setFocusable(false);
        botonSeleccionarImputacion.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonSeleccionarImputacion.setName("botonSeleccionarImputacion"); // NOI18N
        botonSeleccionarImputacion.setPreferredSize(new java.awt.Dimension(200, 24));
        //botonSeleccionarImputacion.setEnabled(false);
        botonSeleccionarImputacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarImputacionActionPerformed(evt);
            }
        });
        panelSoportesresoluciones.add(botonSeleccionarImputacion);

        jLabel75.setPreferredSize(new java.awt.Dimension(20, 25));
        panelSoportesresoluciones.add(jLabel75);

        jSeparator17.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator17.setPreferredSize(new java.awt.Dimension(20, 25));
        panelSoportesresoluciones.add(jSeparator17);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField4.setEnabled(false);
        jTextField4.setFocusable(false);
        jTextField4.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField4.setOpaque(false);
        jTextField4.setPreferredSize(new java.awt.Dimension(535, 25));
        panelSoportesresoluciones.add(jTextField4);

        jLabel72.setPreferredSize(new java.awt.Dimension(790, 15));
        panelSoportesresoluciones.add(jLabel72);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(790, 70));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CUENTA");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel3.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel2.add(jLabel3);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ACTIVIDAD");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel4.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel2.add(jLabel4);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("SUBGRUPO");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel9.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel2.add(jLabel9);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("C. COSTOS");
        jLabel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel21.setPreferredSize(new java.awt.Dimension(95, 25));
        jPanel2.add(jLabel21);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("C. INFO");
        jLabel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel22.setPreferredSize(new java.awt.Dimension(95, 25));
        jPanel2.add(jLabel22);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("CUENTA INTERNA");
        jLabel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel23.setPreferredSize(new java.awt.Dimension(125, 25));
        jPanel2.add(jLabel23);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("VALOR");
        jLabel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel24.setPreferredSize(new java.awt.Dimension(160, 25));
        jPanel2.add(jLabel24);

        cuenta.setBackground(ClaseGeneral.campo);
        cuenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cuenta.setText("0");
        cuenta.setMargin(new java.awt.Insets(2, 4, 2, 4));
        cuenta.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel2.add(cuenta);

        actividad.setBackground(ClaseGeneral.campo);
        actividad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        actividad.setText("0");
        actividad.setMargin(new java.awt.Insets(2, 4, 2, 4));
        actividad.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel2.add(actividad);

        subgrupo.setBackground(ClaseGeneral.campo);
        subgrupo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subgrupo.setModel(ClaseGeneral.controlSubgrupo.COMBOCodigoInSubgrupoBy());
        subgrupo.setSelectedItem("0");
        subgrupo.setOpaque(false);
        subgrupo.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel2.add(subgrupo);

        ccostos.setBackground(ClaseGeneral.campo);
        ccostos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ccostos.setText("0");
        ccostos.setMargin(new java.awt.Insets(2, 4, 2, 4));
        ccostos.setPreferredSize(new java.awt.Dimension(95, 25));
        jPanel2.add(ccostos);

        cinfo.setBackground(ClaseGeneral.campo);
        cinfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cinfo.setModel(ClaseGeneral.controlCinfo.COMBOCodigoInCinfoBy());
        cinfo.setSelectedItem("0");
        cinfo.setOpaque(false);
        cinfo.setPreferredSize(new java.awt.Dimension(95, 25));
        jPanel2.add(cinfo);

        cuentainterna.setBackground(ClaseGeneral.campo);
        cuentainterna.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cuentainterna.setModel(ClaseGeneral.controlCuentainterna.COMBOCodigoInCuentainternaBy());
        cuentainterna.setSelectedItem("0");
        cuentainterna.setOpaque(false);
        cuentainterna.setPreferredSize(new java.awt.Dimension(125, 25));
        jPanel2.add(cuentainterna);

        valorSoporte.setBackground(ClaseGeneral.campo);
        valorSoporte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valorSoporte.setText("0");
        valorSoporte.setMargin(new java.awt.Insets(2, 4, 2, 4));
        valorSoporte.setPreferredSize(new java.awt.Dimension(160, 25));
        valorSoporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldKeyReleased(evt);
            }
        });
        jPanel2.add(valorSoporte);

        panelSoportesresoluciones.add(jPanel2);

        jLabel74.setPreferredSize(new java.awt.Dimension(790, 15));
        panelSoportesresoluciones.add(jLabel74);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(790, 300));

        jTableImputacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CUENTA", "ACTIVIDAD", "SUBGRUPO", "C. COSTOS", "C. INFO", "CUENTA INTERNA", "VALOR", "ACCION"
            }
        ));
        jTableImputacion.setEnabled(false);
        jTableImputacion.setFocusable(false);
        jTableImputacion.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTableImputacion.setRowHeight(20);
        jTableImputacion.setSelectionBackground(ClaseGeneral.campo);
        jScrollPane1.setViewportView(jTableImputacion);

        panelSoportesresoluciones.add(jScrollPane1);

        jTabbedPane.addTab("FORMA DE PAGO", panelSoportesresoluciones);

        add(jTabbedPane);
        jTabbedPane.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldFocusGained
        javax.swing.JTextField componente = (javax.swing.JTextField) evt.getComponent();
        componente.selectAll();
        componente.requestFocus();
    }//GEN-LAST:event_TextFieldFocusGained

    private void TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldKeyReleased
        try {
            try {
                valor.setText(ClaseInformacion.formatoDecimal.format(Long.parseLong(valor.getText().trim().replace(".", ""))));
                soporte.setText(ClaseInformacion.formatoEntero.format(Long.parseLong(soporte.getText().trim().replace(".", ""))));
                valorSoporte.setText(ClaseInformacion.formatoDecimal.format(Long.parseLong(valorSoporte.getText().trim().replace(".", ""))));
            } catch (Exception ex) {
                Logger.getLogger(PanelPolizas.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (Exception ex) {
            Logger.getLogger(PanelPolizas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TextFieldKeyReleased

    private void ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxItemStateChanged
        try {
            salario = ClaseGeneral.controlTerceros.findSalarioInTercerosById("" + fktercero.getText());
            diario = ClaseGeneral.controlTerceros.CALCLiquidacionViativosInTercerosBySalarioTarifa(
                    ClaseGeneral.controlTerceros.findSalarioInTercerosById("" + fktercero.getText()),
                    "" + tarifa.getSelectedItem());
            textInformacionTercero.setText("TERCERO, SALARIO $" + ClaseInformacion.formatoDecimal.format(Long.parseLong("" + salario))
                    + " - DIARIO $" + ClaseInformacion.formatoDecimal.format(diario));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_ComboBoxItemStateChanged

    private void botonBuscarFkterceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarFkterceroActionPerformed
        javax.swing.JButton componente = (javax.swing.JButton) evt.getSource();
        String eventoFktercero = componente.getName();
        ExternoPanelFktercero panelFktercero = new ExternoPanelFktercero();
        ClaseMensaje.panel(panelFktercero);
        if (eventoFktercero.equals("botonBuscarFktercero")) {
            if (!panelFktercero.fktercero.equals("Seleccione - ")) {
                fktercero.setText(panelFktercero.fktercero);

                try {
                    salario = ClaseGeneral.controlTerceros.findSalarioInTercerosById("" + fktercero.getText());
                    diario = ClaseGeneral.controlTerceros.CALCLiquidacionViativosInTercerosBySalarioTarifa(
                            ClaseGeneral.controlTerceros.findSalarioInTercerosById("" + fktercero.getText()),
                            "" + tarifa.getSelectedItem());
                    textInformacionTercero.setText("TERCERO, SALARIO $" + ClaseInformacion.formatoDecimal.format(Long.parseLong("" + salario))
                            + " - DIARIO $" + ClaseInformacion.formatoDecimal.format(diario));
                } catch (Exception e) {
                }
            }
        }
    }//GEN-LAST:event_botonBuscarFkterceroActionPerformed

    private void botonCALCValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCALCValorActionPerformed
        valor.setText(ClaseInformacion.formatoDecimal.format(ClaseGeneral.controlTercerosresoluciones.CALCLiquidacionviaticosresoluciontercero("" + tarifa.getSelectedItem(),
                Integer.parseInt(fkresolucion.getText()),
                ClaseGeneral.resoluciones.getResolucionPK().getAno(),
                "" + fktercero.getText())));
    }//GEN-LAST:event_botonCALCValorActionPerformed

    private void botonAyuda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAyuda1ActionPerformed
        ClaseMensaje.informacion("<html><body>"
                + "Aplica principalmente en los casos de \"Salidas de Campo\"<br/>"
                + "</body></html>");
    }//GEN-LAST:event_botonAyuda1ActionPerformed

    private void botonAyuda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAyuda2ActionPerformed
        ClaseMensaje.informacion("<html><body>"
                + "Si está utilizando algún tipo de tarifa, y desea calcular el valor<br/>"
                + "dependiendo la Fecha de Inicio y la Fecha de Finalización, y teniendo<br/>"
                + "en cuenta el salario que se encuentra en la base de datos, puede dar<br/>"
                + "clic en el botón Ejecutar, que se encuentra al lado del campo valor."
                + "</body></html>");
    }//GEN-LAST:event_botonAyuda2ActionPerformed

    private void botonCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarActionPerformed
        try {
            if (!fktercero.getText().equals("")) {
                salario = BigDecimal.valueOf(Long.parseLong(ClaseMensaje.ingresar("<html><body>"
                        + "Ingrese el valor del salario<br/>"
                        + "\"Sin puntos ni comas\"<br/>"
                        + "</body></html>")));
                ClaseGeneral.controlTerceros.editSalario("" + fktercero.getText(), salario);

                try {
                    diario = ClaseGeneral.controlTerceros.CALCLiquidacionViativosInTercerosBySalarioTarifa(
                            ClaseGeneral.controlTerceros.findSalarioInTercerosById("" + fktercero.getText()),
                            "" + tarifa.getSelectedItem());

                    textInformacionTercero.setText("TERCERO, SALARIO $" + ClaseInformacion.formatoDecimal.format(Long.parseLong("" + ClaseGeneral.controlTerceros.findSalarioInTercerosById("" + fktercero.getText())))
                            + " - DIARIO $" + ClaseInformacion.formatoDecimal.format(diario));

                    ClaseGeneral.tercerosresoluciones.setSalario(salario);
                    ClaseGeneral.tercerosresoluciones.setDiario(diario);

                } catch (Exception e) {
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_botonCambiarActionPerformed

    private void botonSeleccionarImputacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarImputacionActionPerformed
        javax.swing.JButton componente = (javax.swing.JButton) evt.getSource();
        String evento = componente.getName();
        ExternoPanelBuscarImputacion panelBuscarImputacion = new ExternoPanelBuscarImputacion();
        ClaseMensaje.panel(panelBuscarImputacion);

        if (evento.equals("botonSeleccionarImputacion")) {
            if (!panelBuscarImputacion.soporte.equals("Seleccione - ")) {
                StringTokenizer st = new StringTokenizer(panelBuscarImputacion.soporte.trim(), "-");
                while (st.hasMoreTokens()) {
                    listaSoporte.add(st.nextToken().trim());
                }
                cuenta.setText("" + listaSoporte.get(0));
                actividad.setText("" + listaSoporte.get(1));
                subgrupo.setSelectedItem("" + listaSoporte.get(2));
                ccostos.setText("" + listaSoporte.get(3));
                cinfo.setSelectedItem("" + listaSoporte.get(4));
                cuentainterna.setSelectedItem("" + listaSoporte.get(5));
                valorSoporte.setText("" + listaSoporte.get(6));
                fksoportecuenta = panelBuscarImputacion.fksoportecuenta;
                fksoportecuentaid = panelBuscarImputacion.fksoportecuentaid;
                fksoportecomprobante = panelBuscarImputacion.fksoportecomprobante;
                fksoportecomprobanteid = panelBuscarImputacion.fksoportecomprobanteid;
                fksoportecomprobanteano = panelBuscarImputacion.fksoportecomprobanteano;

            }
        }
    }//GEN-LAST:event_botonSeleccionarImputacionActionPerformed

    public void metodoInsertar() {
        ClaseGeneral.tercerosresoluciones = new Tercerosresoluciones();
        ClaseGeneral.tercerosresoluciones.setId(0);
        ClaseGeneral.tercerosresoluciones.setAno(ClaseGeneral.resoluciones.getResolucionPK().getAno());
        ClaseGeneral.tercerosresoluciones.setFkresolucion(Integer.parseInt("" + fkresolucion.getText()));
        ClaseGeneral.tercerosresoluciones.setFktercero("" + fktercero.getText());
        ClaseGeneral.tercerosresoluciones.setValor(BigDecimal.valueOf(Long.parseLong("" + valor.getText().trim().replace(".", ""))));
        ClaseGeneral.tercerosresoluciones.setDestino("" + destino.getText());
        ClaseGeneral.tercerosresoluciones.setObjetivo("" + objetivo.getText());
        ClaseGeneral.tercerosresoluciones.setSoporte("" + soporte.getText());
        ClaseGeneral.tercerosresoluciones.setTarifa("" + tarifa.getSelectedItem());
        ClaseGeneral.tercerosresoluciones.setSalario(salario);
        ClaseGeneral.tercerosresoluciones.setDiario(diario);
        ClaseGeneral.tercerosresoluciones.setFkcomprobante("" + soporte.getText());
        ClaseGeneral.tercerosresoluciones.setFkcuenta("" + fkcuenta.getText());

        ClaseGeneral.soportesresoluciones = new Soportesresoluciones();
        ClaseGeneral.soportesresolucionesPK = new SoportesresolucionesPK();
        ClaseGeneral.soportesresolucionesPK.setFkresolucion(Integer.parseInt("" + fkresolucion.getText()));
        ClaseGeneral.soportesresolucionesPK.setId(0);
        ClaseGeneral.soportesresolucionesPK.setAno(ClaseGeneral.resoluciones.getResolucionPK().getAno());
        ClaseGeneral.soportesresoluciones.setSoportesresolucionesPK(ClaseGeneral.soportesresolucionesPK);
        ClaseGeneral.soportesresoluciones.setFksoportecuenta(fksoportecuenta);
        ClaseGeneral.soportesresoluciones.setFksoportecuentaid(fksoportecuentaid);
        ClaseGeneral.soportesresoluciones.setFksoportecomprobante(fksoportecomprobante);
        ClaseGeneral.soportesresoluciones.setFksoportecomprobanteid(fksoportecomprobanteid);
        ClaseGeneral.soportesresoluciones.setFksoportecomprobanteano(fksoportecomprobanteano);
//        ClaseGeneral.soportesresoluciones.setFktercerosresolucion(ClaseGeneral.idTercerosresolucion);
        ClaseGeneral.soportesresoluciones.setCuenta(cuenta.getText());
        ClaseGeneral.soportesresoluciones.setActividad(actividad.getText());
        ClaseGeneral.soportesresoluciones.setSubgrupo("" + subgrupo.getSelectedItem());
        ClaseGeneral.soportesresoluciones.setCcostos(ccostos.getText());
        ClaseGeneral.soportesresoluciones.setCinfo("" + cinfo.getSelectedItem());
        ClaseGeneral.soportesresoluciones.setCuentainterna("" + cuentainterna.getSelectedItem());
        ClaseGeneral.soportesresoluciones.setValor(BigDecimal.valueOf(Long.parseLong("" + valor.getText().trim().replace(".", ""))));

        try {
            ClaseGeneral.controlTercerosresoluciones.create(ClaseGeneral.tercerosresoluciones);
        } catch (Exception ex) {
            Logger.getLogger(PanelTercerosresoluciones.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (ClaseGeneral.controlSoportesresoluciones.verify(ClaseGeneral.soportesresoluciones)) {
            try {
                ClaseGeneral.soportesresoluciones.setFktercerosresolucion(ClaseGeneral.idTercerosresolucion);
                ClaseGeneral.controlSoportesresoluciones.create(ClaseGeneral.soportesresoluciones);
            } catch (Exception ex) {
                Logger.getLogger(PanelTercerosresoluciones.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void metodoConsultar() {
        try {
            id.setText("" + ClaseGeneral.tercerosresoluciones.getId());
//        ano.setText("" + ClaseGeneral.tercerosresolucion.getAno());
            fkresolucion.setText("" + ClaseGeneral.tercerosresoluciones.getFkresolucion());
            fktercero.setText("" + ClaseGeneral.tercerosresoluciones.getFktercero());
            valor.setText("" + ClaseInformacion.formatoDecimal.format(ClaseGeneral.tercerosresoluciones.getValor()));
            destino.setText("" + ClaseGeneral.tercerosresoluciones.getDestino());
            objetivo.setText("" + ClaseGeneral.tercerosresoluciones.getObjetivo());
            soporte.setText("" + ClaseGeneral.tercerosresoluciones.getSoporte());
            tarifa.setSelectedItem("" + ClaseGeneral.tercerosresoluciones.getTarifa());
            salario = ClaseGeneral.tercerosresoluciones.getSalario();
            diario = ClaseGeneral.tercerosresoluciones.getDiario();
            soporte.setText(ClaseGeneral.tercerosresoluciones.getFkcomprobante());
            fkcuenta.setText(ClaseGeneral.tercerosresoluciones.getFkcuenta());

            /**/ metodoMostrarImputacion();

            try {
                textInformacionTercero.setText("TERCERO, SALARIO $" + salario + " - DIARIO $" + diario);
            } catch (Exception e) {
            }
        } catch (Exception ex) {
            Logger.getLogger(PanelResoluciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void metodoActualizar() {
        Tercerosresoluciones tercerosresolucionId = ClaseGeneral.tercerosresoluciones;
        ClaseGeneral.tercerosresoluciones = new Tercerosresoluciones();
//        ClaseGeneral.tercerosresolucion.setId();
        ClaseGeneral.tercerosresoluciones.setAno(ClaseGeneral.resoluciones.getResolucionPK().getAno());
        ClaseGeneral.tercerosresoluciones.setFkresolucion(Integer.parseInt("" + fkresolucion.getText()));
        ClaseGeneral.tercerosresoluciones.setFktercero("" + fktercero.getText());
        ClaseGeneral.tercerosresoluciones.setValor(BigDecimal.valueOf(Long.parseLong("" + valor.getText().trim().replace(".", ""))));
        ClaseGeneral.tercerosresoluciones.setDestino("" + destino.getText());
        ClaseGeneral.tercerosresoluciones.setObjetivo("" + objetivo.getText());
        ClaseGeneral.tercerosresoluciones.setSoporte("" + soporte.getText());
        ClaseGeneral.tercerosresoluciones.setTarifa("" + tarifa.getSelectedItem());
        ClaseGeneral.tercerosresoluciones.setSalario(salario);
        ClaseGeneral.tercerosresoluciones.setDiario(diario);
        ClaseGeneral.tercerosresoluciones.setFkcomprobante("" + soporte.getText());
        ClaseGeneral.tercerosresoluciones.setFkcuenta("" + fkcuenta.getText());

        try {
            ClaseGeneral.controlTercerosresoluciones.edit(ClaseGeneral.tercerosresoluciones, tercerosresolucionId);
        } catch (Exception ex) {
            Logger.getLogger(PanelTercerosresoluciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void metodoEliminar() {
        Tercerosresoluciones tercerosresolucionId = ClaseGeneral.tercerosresoluciones;
        ClaseGeneral.tercerosresoluciones = new Tercerosresoluciones();
        try {
            ClaseGeneral.controlTercerosresoluciones.destroy(tercerosresolucionId);
        } catch (Exception ex) {
            Logger.getLogger(PanelTercerosresoluciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public final void metodoMostrar() {
        BigDecimal valTotal = BigDecimal.ZERO;
        ClaseGeneral.tercerosresoluciones = new Tercerosresoluciones();
        lista = ClaseGeneral.controlTercerosresoluciones.findAllInTercerosresolucionesByFkresolucionAno(ClaseGeneral.resoluciones.getResolucionPK().getId(), ClaseGeneral.resoluciones.getResolucionPK().getAno());

        for (int i = 0; i < 100; i++) {
            jTable.setValueAt("", i, 0);
            jTable.setValueAt("", i, 1);
        }
        int i = 0;
        for (Object lista1 : lista) {
            ClaseGeneral.tercerosresoluciones = (Tercerosresoluciones) lista1;
            jTable.setValueAt("" + ClaseGeneral.tercerosresoluciones.getFktercero(), i, 0);
            jTable.setValueAt("" + ClaseInformacion.formatoDecimal.format(ClaseGeneral.tercerosresoluciones.getValor()), i, 1);
            valTotal = valTotal.add(ClaseGeneral.tercerosresoluciones.getValor());
            i++;
        }
        jTable.clearSelection();
        jTable.getColumnModel().getColumn(0).setPreferredWidth(710);
        jTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        valorTotal.setText("" + ClaseInformacion.formatoDecimal.format(valTotal));
    }

    public void metodoMostrarImputacion() {
        BigDecimal valTotal = BigDecimal.ZERO;
        ClaseGeneral.soportesresoluciones = new Soportesresoluciones();
        lista = ClaseGeneral.controlSoportesresoluciones.findAllInSoportesresolucionesByFkresolucionAnoFktercerosresolucion(Integer.parseInt(fkresolucion.getText()), ClaseGeneral.resoluciones.getResolucionPK().getAno(), Integer.parseInt(id.getText()));

        jTableImputacion.getColumnModel().getColumn(6).setCellRenderer(informacion.modeloDerecha);

        for (int i = 0; i < 100; i++) {
            jTableImputacion.setValueAt("", i, 0);
            jTableImputacion.setValueAt("", i, 1);
            jTableImputacion.setValueAt("", i, 2);
            jTableImputacion.setValueAt("", i, 3);
            jTableImputacion.setValueAt("", i, 4);
            jTableImputacion.setValueAt("", i, 5);
            jTableImputacion.setValueAt("", i, 6);
            jTableImputacion.setValueAt("BORRAR", i, 7);
        }

        int i = 0;
        for (Object lista1 : lista) {
            ClaseGeneral.soportesresoluciones = (Soportesresoluciones) lista1;
            jTableImputacion.setValueAt("" + ClaseGeneral.soportesresoluciones.getCuenta(), i, 0);
            jTableImputacion.setValueAt("" + ClaseGeneral.soportesresoluciones.getActividad(), i, 1);
            jTableImputacion.setValueAt("" + ClaseGeneral.soportesresoluciones.getSubgrupo(), i, 2);
            jTableImputacion.setValueAt("" + ClaseGeneral.soportesresoluciones.getCcostos(), i, 3);
            jTableImputacion.setValueAt("" + ClaseGeneral.soportesresoluciones.getCinfo(), i, 4);
            jTableImputacion.setValueAt("" + ClaseGeneral.soportesresoluciones.getCuentainterna(), i, 5);
            jTableImputacion.setValueAt("" + ClaseInformacion.formatoDecimal.format(ClaseGeneral.soportesresoluciones.getValor()), i, 6);
            valTotal = valTotal.add(ClaseGeneral.soportesresoluciones.getValor());
            i++;
        }

        jTableImputacion.clearSelection();
        jTableImputacion.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTableImputacion.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableImputacion.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableImputacion.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableImputacion.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTableImputacion.getColumnModel().getColumn(5).setPreferredWidth(110);
        jTableImputacion.getColumnModel().getColumn(6).setPreferredWidth(100);
        jTableImputacion.getColumnModel().getColumn(7).setPreferredWidth(100);

        jTableImputacion.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    JTable target = (JTable) e.getSource();
                    int row = target.getSelectedRow();
                    int column = target.getSelectedColumn();
                    System.out.println("row " + row + " column " + column);
//                    if()
                    // do some stuff
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField actividad;
    private javax.swing.JButton botonAyuda1;
    private javax.swing.JButton botonAyuda2;
    private javax.swing.JButton botonBuscarFktercero;
    private javax.swing.JButton botonCALCValor;
    public javax.swing.JButton botonCambiar;
    public javax.swing.JButton botonSeleccionarImputacion;
    public javax.swing.JTextField ccostos;
    public javax.swing.JComboBox cinfo;
    public javax.swing.JTextField cuenta;
    public javax.swing.JComboBox cuentainterna;
    private javax.swing.JTextArea destino;
    private javax.swing.JTextField fkcomprobante;
    private javax.swing.JTextField fkcuenta;
    private javax.swing.JTextField fkresolucion;
    private javax.swing.JTextField fktercero;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTarifa;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDestino;
    private javax.swing.JPanel jPanelObjetivo;
    private javax.swing.JPanel jPanelOtraFormaPago;
    public javax.swing.JScrollPane jScrollPane;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneDestino;
    private javax.swing.JScrollPane jScrollPaneDestino1;
    private javax.swing.JScrollPane jScrollPaneObjetivo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JTabbedPane jTabbedPane;
    public javax.swing.JTable jTable;
    public javax.swing.JTable jTableImputacion;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextArea objetivo;
    private javax.swing.JPanel panelSoportesresoluciones;
    private javax.swing.JPanel panelTercero;
    private javax.swing.JTextArea soporte;
    public javax.swing.JComboBox subgrupo;
    private javax.swing.JComboBox tarifa;
    private javax.swing.JTextField textInformacionTercero;
    private javax.swing.JTextField valor;
    private javax.swing.JTextField valorSoporte;
    private javax.swing.JTextField valorTotal;
    // End of variables declaration//GEN-END:variables
}
