/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * PanelSoportescontratosContratos.java
 *
 * Created on 16/01/2012, 05:14:48 PM
 */
package frame;

import clases.ClaseGeneral;
import clases.ClaseInformacion;
import clases.ClaseMensaje;
import entidades.Contratos;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jhon Lopez
 */
public class PanelIniciocontratos extends javax.swing.JPanel {

    private List lista = new ArrayList();
    private ClaseInformacion informacion = new ClaseInformacion();

    /**
     * Creates new form PanelSoportescontratosContratos
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public PanelIniciocontratos() {
        initComponents();

        fechainicio.setFormats(new SimpleDateFormat("yyyy-MM-dd"));
        fechaterminacion.setFormats(new SimpleDateFormat("yyyy-MM-dd"));
        fechaactainicio.setFormats(new SimpleDateFormat("yyyy-MM-dd"));
        
        fechainicio.setDate(new Date(ClaseInformacion.calendario.getTimeInMillis()));
        fechaactainicio.setDate(new Date(ClaseInformacion.calendario.getTimeInMillis()));

        Calendar cal = Calendar.getInstance();
        cal.setTime(fechainicio.getDate());
        cal.add(Calendar.MONTH, 1);
        fechaterminacion.setDate(new Date(cal.getTimeInMillis()));

        fkcontrato.setText(ClaseGeneral.contratos.getContrato());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fkcontrato = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        fechainicio = new org.jdesktop.swingx.JXDatePicker();
        jLabel26 = new javax.swing.JLabel();
        botonAyuda1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        plazo = new javax.swing.JTextField();
        unidadduracion = new javax.swing.JComboBox();
        botonCalcular = new javax.swing.JButton();
        jTextField17 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        fechaterminacion = new org.jdesktop.swingx.JXDatePicker();
        jLabel27 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        fechaactainicio = new org.jdesktop.swingx.JXDatePicker();
        jLabel31 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        observacionesactainicio = new javax.swing.JTextArea();

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("C. COSTOS");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel7.setPreferredSize(new java.awt.Dimension(90, 25));

        setName("panelIniciocontratos"); // NOI18N
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("NÚMERO DEL CONTRATO : ");
        jLabel1.setPreferredSize(new java.awt.Dimension(160, 25));
        add(jLabel1);

        fkcontrato.setBackground(ClaseGeneral.verde);
        fkcontrato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fkcontrato.setForeground(ClaseGeneral.rojo);
        fkcontrato.setFocusable(false);
        fkcontrato.setMargin(new java.awt.Insets(2, 4, 2, 4));
        fkcontrato.setPreferredSize(new java.awt.Dimension(300, 25));
        add(fkcontrato);

        jTextField15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField15.setEnabled(false);
        jTextField15.setFocusable(false);
        jTextField15.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField15.setOpaque(false);
        jTextField15.setPreferredSize(new java.awt.Dimension(340, 25));
        add(jTextField15);

        jLabel72.setPreferredSize(new java.awt.Dimension(810, 25));
        add(jLabel72);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PLAZO DE EJECUCIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(810, 120));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel11.setText("FECHA INICIO DEL CONTRATO : ");
        jLabel11.setPreferredSize(new java.awt.Dimension(185, 25));
        jPanel2.add(jLabel11);

        jPanel6.setBackground(ClaseGeneral.campo);
        jPanel6.setMaximumSize(new java.awt.Dimension(140, 25));
        jPanel6.setMinimumSize(new java.awt.Dimension(140, 25));
        jPanel6.setPreferredSize(new java.awt.Dimension(140, 25));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        fechainicio.setFocusable(false);
        fechainicio.setMaximumSize(new java.awt.Dimension(120, 25));
        fechainicio.setMinimumSize(new java.awt.Dimension(120, 25));
        fechainicio.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel6.add(fechainicio);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel26.setMaximumSize(new java.awt.Dimension(20, 26));
        jLabel26.setMinimumSize(new java.awt.Dimension(20, 26));
        jLabel26.setPreferredSize(new java.awt.Dimension(20, 26));
        jPanel6.add(jLabel26);

        jPanel2.add(jPanel6);

        botonAyuda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos24/info.png"))); // NOI18N
        botonAyuda1.setFocusable(false);
        botonAyuda1.setName("botonAyuda1"); // NOI18N
        botonAyuda1.setPreferredSize(new java.awt.Dimension(25, 24));
        botonAyuda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAyudaActionPerformed(evt);
            }
        });
        jPanel2.add(botonAyuda1);

        jLabel17.setPreferredSize(new java.awt.Dimension(20, 25));
        jPanel2.add(jLabel17);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(20, 25));
        jPanel2.add(jSeparator3);

        jLabel9.setText("PLAZO : ");
        jLabel9.setPreferredSize(new java.awt.Dimension(50, 25));
        jPanel2.add(jLabel9);

        plazo.setBackground(ClaseGeneral.campo);
        plazo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        plazo.setText("1");
        plazo.setMargin(new java.awt.Insets(2, 4, 2, 4));
        plazo.setName("PLAZO"); // NOI18N
        plazo.setPreferredSize(new java.awt.Dimension(100, 25));
        plazo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldFocusGained(evt);
            }
        });
        plazo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldKeyReleased(evt);
            }
        });
        jPanel2.add(plazo);

        unidadduracion.setBackground(ClaseGeneral.campo);
        unidadduracion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        unidadduracion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "DÍAS", "SEMANAS", "MESES", "AÑOS" }));
        unidadduracion.setSelectedItem("MESES");
        unidadduracion.setName("UNIDADDURACION"); // NOI18N
        unidadduracion.setPreferredSize(new java.awt.Dimension(120, 24));
        unidadduracion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxStateChanged(evt);
            }
        });
        jPanel2.add(unidadduracion);

        botonCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos24/process.png"))); // NOI18N
        botonCalcular.setFocusable(false);
        botonCalcular.setPreferredSize(new java.awt.Dimension(25, 24));
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });
        jPanel2.add(botonCalcular);

        jTextField17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField17.setEnabled(false);
        jTextField17.setFocusable(false);
        jTextField17.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField17.setOpaque(false);
        jTextField17.setPreferredSize(new java.awt.Dimension(55, 25));
        jPanel2.add(jTextField17);

        jLabel15.setText("FECHA TERMINACIÓN DEL CONTRATO : ");
        jLabel15.setPreferredSize(new java.awt.Dimension(230, 25));
        jPanel2.add(jLabel15);

        jPanel7.setBackground(ClaseGeneral.campo);
        jPanel7.setMaximumSize(new java.awt.Dimension(140, 25));
        jPanel7.setMinimumSize(new java.awt.Dimension(140, 25));
        jPanel7.setPreferredSize(new java.awt.Dimension(140, 25));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        fechaterminacion.setFocusable(false);
        fechaterminacion.setMaximumSize(new java.awt.Dimension(120, 25));
        fechaterminacion.setMinimumSize(new java.awt.Dimension(120, 25));
        fechaterminacion.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel7.add(fechaterminacion);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel27.setMaximumSize(new java.awt.Dimension(20, 26));
        jLabel27.setMinimumSize(new java.awt.Dimension(20, 26));
        jLabel27.setPreferredSize(new java.awt.Dimension(20, 26));
        jPanel7.add(jLabel27);

        jPanel2.add(jPanel7);

        jTextField18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField18.setEnabled(false);
        jTextField18.setFocusable(false);
        jTextField18.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField18.setOpaque(false);
        jTextField18.setPreferredSize(new java.awt.Dimension(405, 25));
        jPanel2.add(jTextField18);

        jLabel30.setText("FECHA ACTA DE INICIO : ");
        jLabel30.setPreferredSize(new java.awt.Dimension(190, 25));
        jPanel2.add(jLabel30);

        jPanel27.setBackground(ClaseGeneral.campo);
        jPanel27.setMaximumSize(new java.awt.Dimension(140, 25));
        jPanel27.setMinimumSize(new java.awt.Dimension(140, 25));
        jPanel27.setPreferredSize(new java.awt.Dimension(140, 25));
        jPanel27.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        fechaactainicio.setFocusable(false);
        fechaactainicio.setMaximumSize(new java.awt.Dimension(120, 25));
        fechaactainicio.setMinimumSize(new java.awt.Dimension(120, 25));
        fechaactainicio.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel27.add(fechaactainicio);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel31.setMaximumSize(new java.awt.Dimension(20, 26));
        jLabel31.setMinimumSize(new java.awt.Dimension(20, 26));
        jLabel31.setPreferredSize(new java.awt.Dimension(20, 26));
        jPanel27.add(jLabel31);

        jPanel2.add(jPanel27);

        jTextField19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField19.setEnabled(false);
        jTextField19.setFocusable(false);
        jTextField19.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField19.setOpaque(false);
        jTextField19.setPreferredSize(new java.awt.Dimension(445, 25));
        jPanel2.add(jTextField19);

        add(jPanel2);

        jLabel73.setPreferredSize(new java.awt.Dimension(810, 25));
        add(jLabel73);

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OBSERVACIONES ACTA DE INICIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        jPanel14.setPreferredSize(new java.awt.Dimension(810, 100));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setPreferredSize(new java.awt.Dimension(430, 70));

        observacionesactainicio.setBackground(ClaseGeneral.campo);
        observacionesactainicio.setColumns(20);
        observacionesactainicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        observacionesactainicio.setLineWrap(true);
        observacionesactainicio.setRows(5);
        observacionesactainicio.setWrapStyleWord(true);
        observacionesactainicio.setMargin(new java.awt.Insets(2, 5, 2, 5));
        observacionesactainicio.setPreferredSize(new java.awt.Dimension(430, 70));
        jScrollPane3.setViewportView(observacionesactainicio);

        jPanel14.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        add(jPanel14);
        jPanel14.getAccessibleContext().setAccessibleName("OBSERVACIONES ACTA DE INICIO");
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxStateChanged
        javax.swing.JComboBox componente = (javax.swing.JComboBox) evt.getSource();

        if (componente.getName().equals("UNIDADDURACION")) {
            metodoCalcularFechaTerminacion();
        }
    }//GEN-LAST:event_ComboBoxStateChanged

    private void TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldFocusGained
        javax.swing.JTextField componente = (javax.swing.JTextField) evt.getComponent();
        componente.selectAll();
        componente.requestFocus();
    }//GEN-LAST:event_TextFieldFocusGained

    private void TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldKeyReleased
        javax.swing.JTextField componente = (javax.swing.JTextField) evt.getComponent();

        try {
            if (componente.getName().equals("PLAZO")) {
                metodoCalcularFechaTerminacion();
            }
        } catch (Exception ex) {
            Logger.getLogger(PanelPolizas.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            plazo.setText(ClaseInformacion.formatoEntero.format(Long.parseLong(plazo.getText().trim().replace(".", ""))));
        } catch (Exception ex) {
            Logger.getLogger(PanelPolizas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TextFieldKeyReleased

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        metodoCalcularFechaTerminacion();
    }//GEN-LAST:event_botonCalcularActionPerformed

    private void botonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAyudaActionPerformed
        javax.swing.JButton componente = (javax.swing.JButton) evt.getSource();
        String eventoAyuda = componente.getName();

        if (eventoAyuda.equals("botonAyuda1")) {
            ClaseMensaje.informacion("Incluídas las prórrogas");
        }
    }//GEN-LAST:event_botonAyudaActionPerformed

    public void metodoInsertar() {
    }

    public void metodoConsultar() {
        try {
            fkcontrato.setText(ClaseGeneral.contratos.getContrato());
            fechainicio.setDate(ClaseGeneral.contratos.getFechainicio());
            unidadduracion.setSelectedItem(ClaseGeneral.contratos.getUnidadduracion());
            plazo.setText(ClaseGeneral.contratos.getPlazo());
            fechaterminacion.setDate(ClaseGeneral.contratos.getFechaterminacion());
            fechaactainicio.setDate(ClaseGeneral.contratos.getFechaactainicio()); // BORRAR
            observacionesactainicio.setText(ClaseGeneral.contratos.getObservacionesactainicio());
        
            fkcontrato.setFocusable(false);
        } catch (Exception ex) {
            Logger.getLogger(PanelResoluciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void metodoActualizar() {
        Contratos contratosId = ClaseGeneral.contratos;

        ClaseGeneral.contratos.setFechainicio(fechainicio.getDate());
        ClaseGeneral.contratos.setUnidadduracion("" + unidadduracion.getSelectedItem());
        ClaseGeneral.contratos.setPlazo(plazo.getText());
        ClaseGeneral.contratos.setFechaterminacion(fechaterminacion.getDate());
        ClaseGeneral.contratos.setFechaactainicio(fechaactainicio.getDate());
        ClaseGeneral.contratos.setObservacionesactainicio(observacionesactainicio.getText());

        try {
            ClaseGeneral.controlContratos.editIniciocontratos(ClaseGeneral.contratos, contratosId);
        } catch (Exception ex) {
            Logger.getLogger(PanelIniciocontratos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void metodoEliminar() {
        try {
        } catch (Exception ex) {
            Logger.getLogger(PanelIniciocontratos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void metodoCalcularFechaTerminacion() {
        int intPlazo;
        try {
            intPlazo = Integer.parseInt(plazo.getText());
        } catch (Exception ex) {
            plazo.setText("0");
            intPlazo = 0;
        }

        Calendar cal = Calendar.getInstance();
        cal.setTime(fechainicio.getDate());
        if (unidadduracion.getSelectedItem().equals("DÍAS")) {
            cal.add(Calendar.DATE, intPlazo - 1);
        } else if (unidadduracion.getSelectedItem().equals("SEMANAS")) {
            cal.add(Calendar.DATE, 7 * intPlazo);
        } else if (unidadduracion.getSelectedItem().equals("MESES")) {
            cal.add(Calendar.MONTH, intPlazo);
        } else if (unidadduracion.getSelectedItem().equals("AÑOS")) {
            cal.add(Calendar.YEAR, intPlazo);
        }
        fechaterminacion.setDate(new Date(cal.getTimeInMillis()));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAyuda1;
    private javax.swing.JButton botonCalcular;
    private org.jdesktop.swingx.JXDatePicker fechaactainicio;
    private org.jdesktop.swingx.JXDatePicker fechainicio;
    public org.jdesktop.swingx.JXDatePicker fechaterminacion;
    private javax.swing.JTextField fkcontrato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextArea observacionesactainicio;
    private javax.swing.JTextField plazo;
    private javax.swing.JComboBox unidadduracion;
    // End of variables declaration//GEN-END:variables
}
