/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelAnexosterceros.java
 *
 * Created on 16/01/2012, 05:14:48 PM
 */
package frame;

import clases.ClaseGeneral;
import clases.ClaseInformacion;
import clases.ClaseMensaje;
import entidades.Anexosterceros;
import entidades.AnexostercerosPK;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.net.URL;
import java.net.URLConnection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import neuranas.SFTP;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Jhon Lopez
 */
public class PanelAnexosterceros extends javax.swing.JPanel {

    private List lista = new ArrayList();
    private ClaseInformacion informacion = new ClaseInformacion();
    FileNameExtensionFilter filter = new FileNameExtensionFilter("pdf", "PDF");
    private File file = null;
    private SFTP sftp = new SFTP();

    /**
     * Creates new form PanelAnexosterceros
     */
    public PanelAnexosterceros() {
        initComponents();

        documento.setEditable(true);
        AutoCompleteDecorator.decorate(documento);

        fecha.setFormats(new SimpleDateFormat("yyyy-MM-dd"));
        fecha.setDate(new Date(ClaseInformacion.calendario.getTimeInMillis()));

        fktercero.setText(ClaseGeneral.terceros.getId() + " - " + ClaseGeneral.terceros.getNombre());

        /**/        file = null;
        metodoMostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        fktercero = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        documento = new javax.swing.JComboBox();
        jLabel73 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel50 = new javax.swing.JLabel();
        fecha = new org.jdesktop.swingx.JXDatePicker();
        jTextField28 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        archivo = new javax.swing.JTextField();
        botonExaminar = new javax.swing.JButton();
        jLabel74 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        botonVer = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        jFileChooser.setCurrentDirectory(new java.io.File("C:\\Users\\Admin\\Documents\\Mis escaneos"));
        jFileChooser.setFileFilter(filter);

        setName("panelAnexosterceros"); // NOI18N
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("CÉDULA / NIT DEL TERCERO : ");
        jLabel1.setPreferredSize(new java.awt.Dimension(180, 25));
        add(jLabel1);

        fktercero.setBackground(ClaseGeneral.verde);
        fktercero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fktercero.setForeground(ClaseGeneral.rojo);
        fktercero.setFocusable(false);
        fktercero.setMargin(new java.awt.Insets(2, 4, 2, 4));
        fktercero.setName("fktercero"); // NOI18N
        fktercero.setPreferredSize(new java.awt.Dimension(560, 25));
        add(fktercero);

        jTextField15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField15.setEnabled(false);
        jTextField15.setFocusable(false);
        jTextField15.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField15.setOpaque(false);
        jTextField15.setPreferredSize(new java.awt.Dimension(60, 25));
        add(jTextField15);

        jLabel48.setText("TIPO DOCUMENTO : ");
        jLabel48.setPreferredSize(new java.awt.Dimension(130, 25));
        add(jLabel48);

        documento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        documento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Boletín de responsables fiscales (1 mes)", "Certificado de antecedentes disciplinarios (3 meses)", "Certificado de cámara y comercio (2 meses)", "Constancia afiliación pensión y cesantías", "Constancia afiliación a seguridad social", "Constancia cuenta bancaria", "Fotocopia de la cedula de ciudadanía", "Fotocopia de la libreta militar", "*Informe de Recomendación", "Pago de aporte a seguridad social", "Pasado judicial - DAS (12 meses)", "Registro único tributario R.U.T", "Otros" }));
        documento.setPreferredSize(new java.awt.Dimension(410, 25));
        add(documento);

        jLabel73.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jLabel73);

        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator16.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jSeparator16);

        jLabel50.setText("FECHA : ");
        jLabel50.setPreferredSize(new java.awt.Dimension(60, 25));
        add(jLabel50);

        fecha.setFocusable(false);
        fecha.setMaximumSize(new java.awt.Dimension(120, 25));
        fecha.setMinimumSize(new java.awt.Dimension(120, 25));
        fecha.setPreferredSize(new java.awt.Dimension(120, 25));
        add(fecha);

        jTextField28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField28.setEnabled(false);
        jTextField28.setFocusable(false);
        jTextField28.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField28.setOpaque(false);
        jTextField28.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jTextField28);

        jLabel25.setText("RUTA ARCHIVO : ");
        jLabel25.setPreferredSize(new java.awt.Dimension(105, 25));
        add(jLabel25);

        archivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        archivo.setMargin(new java.awt.Insets(2, 4, 2, 4));
        archivo.setPreferredSize(new java.awt.Dimension(510, 25));
        add(archivo);

        botonExaminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos24/attachment.png"))); // NOI18N
        botonExaminar.setFocusable(false);
        botonExaminar.setPreferredSize(new java.awt.Dimension(25, 24));
        botonExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExaminarActionPerformed(evt);
            }
        });
        add(botonExaminar);

        jLabel74.setPreferredSize(new java.awt.Dimension(15, 25));
        add(jLabel74);

        jSeparator17.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator17.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jSeparator17);

        botonVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos24/text_page.png"))); // NOI18N
        botonVer.setText("Ver pdf");
        botonVer.setFocusable(false);
        botonVer.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonVer.setPreferredSize(new java.awt.Dimension(110, 24));
        botonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerActionPerformed(evt);
            }
        });
        add(botonVer);

        jLabel7.setText("DESCRIPCION : ");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 25));
        add(jLabel7);

        descripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descripcion.setMargin(new java.awt.Insets(2, 4, 2, 4));
        descripcion.setPreferredSize(new java.awt.Dimension(705, 25));
        add(descripcion);

        jLabel71.setPreferredSize(new java.awt.Dimension(810, 25));
        add(jLabel71);

        jScrollPane.setPreferredSize(new java.awt.Dimension(810, 415));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "TIPO ANEXO", "FECHA", "ARCHIVO"
            }
        ));
        jTable.setEnabled(false);
        jTable.setFocusable(false);
        jTable.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTable.setRowHeight(20);
        jTable.setSelectionBackground(ClaseGeneral.campo);
        jScrollPane.setViewportView(jTable);

        add(jScrollPane);
    }// </editor-fold>//GEN-END:initComponents

    private void botonExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExaminarActionPerformed
        try {
            int accion = jFileChooser.showOpenDialog(this);
            if (accion == JFileChooser.APPROVE_OPTION) {
                file = jFileChooser.getSelectedFile();
                archivo.setText(file.getPath());
            } else {
            }
        } catch (Exception e) {
            ClaseMensaje.error("Error al abrir el archivo.\n" + e);
        }
    }//GEN-LAST:event_botonExaminarActionPerformed

    private void botonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerActionPerformed
        try {
            if (file != null) {
                Desktop.getDesktop().open(this.file);
            } else {
                URL url = new URL("http://" + ClaseGeneral.servidor + "/UmVbZxut/archivos/" + archivo.getText());
                String extension = archivo.getText().substring(archivo.getText().lastIndexOf("."));
                URLConnection urlCon = url.openConnection();
                InputStream is = urlCon.getInputStream();
                long aleatorio = ClaseInformacion.LongAletario();
                FileOutputStream fos = new FileOutputStream("archivo_" + aleatorio + "" + extension);
                byte[] array = new byte[10000];
                int leido = is.read(array);
                while (leido > 0) {
                    fos.write(array, 0, leido);
                    leido = is.read(array);
                }

                is.close();
                fos.close();

                File fileAux = new File("archivo_" + aleatorio + "" + extension);
                if (fileAux.getAbsoluteFile().exists()) {
                    Desktop.getDesktop().open(fileAux);
                } else {
                }
            }
        } catch (Exception e) {
            ClaseMensaje.error("Error al abrir el archivo.\n" + e);
        }
    }//GEN-LAST:event_botonVerActionPerformed

    public void metodoInsertar() {
        try {
            String extension = archivo.getText().substring(archivo.getText().lastIndexOf("."));
            String nombreArchivo = fktercero.getText().toString().substring(0, fktercero.getText().toString().indexOf(" - ")) + "_" + documento.getSelectedItem() + "_" + ClaseInformacion.ConvertirFecha(fecha.getDate());
            nombreArchivo = nombreArchivo.toUpperCase().trim().replace(" ", "").replace(":", "") + "" + extension;
            nombreArchivo = ClaseInformacion.EliminarAcentosYDemas(nombreArchivo);
            nombreArchivo = nombreArchivo.replace("*", "");
            sftp.subir(file.getPath(), nombreArchivo);
            archivo.setText(nombreArchivo);
        } catch (Exception ex) {
            Logger.getLogger(PanelAnexoscontratos.class.getName()).log(Level.SEVERE, null, ex);
        }

        ClaseGeneral.anexosterceros = new Anexosterceros();
        ClaseGeneral.anexostercerosPK = new AnexostercerosPK();
        ClaseGeneral.anexostercerosPK.setFktercero(fktercero.getText());
        ClaseGeneral.anexostercerosPK.setFecha(fecha.getDate());
        ClaseGeneral.anexostercerosPK.setDocumento("" + documento.getSelectedItem());
        ClaseGeneral.anexosterceros.setAnexostercerosPK(ClaseGeneral.anexostercerosPK);
        ClaseGeneral.anexosterceros.setArchivo(archivo.getText());
        ClaseGeneral.anexosterceros.setDescripcion(descripcion.getText());

        try {
            ClaseGeneral.controlAnexosterceros.create(ClaseGeneral.anexosterceros);
        } catch (Exception ex) {
            Logger.getLogger(PanelAnexosterceros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void metodoConsultar() {
        try {
            fktercero.setText(ClaseGeneral.anexosterceros.getAnexostercerosPK().getFktercero());
            documento.setSelectedItem(ClaseGeneral.anexosterceros.getAnexostercerosPK().getDocumento());
            fecha.setDate(ClaseGeneral.anexosterceros.getAnexostercerosPK().getFecha());
            archivo.setText(ClaseGeneral.anexosterceros.getArchivo());
            descripcion.setText(ClaseGeneral.anexosterceros.getDescripcion());

            fktercero.setFocusable(false);
            documento.setEnabled(false);
            fecha.setEditable(false);
            archivo.setFocusable(false);
            botonExaminar.setEnabled(false);
        } catch (Exception ex) {
            Logger.getLogger(PanelResoluciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void metodoActualizar() {
        Anexosterceros anexostercerosId = ClaseGeneral.anexosterceros;
        anexostercerosId.setAnexostercerosPK(ClaseGeneral.anexosterceros.getAnexostercerosPK());
        ClaseGeneral.anexosterceros = new Anexosterceros();
        ClaseGeneral.anexostercerosPK = new AnexostercerosPK();
        ClaseGeneral.anexostercerosPK.setFktercero(fktercero.getText());
        ClaseGeneral.anexostercerosPK.setFecha(fecha.getDate());
        ClaseGeneral.anexostercerosPK.setDocumento("" + documento.getSelectedItem());
        ClaseGeneral.anexosterceros.setAnexostercerosPK(ClaseGeneral.anexostercerosPK);
        ClaseGeneral.anexosterceros.setArchivo(archivo.getText());
        ClaseGeneral.anexosterceros.setDescripcion(descripcion.getText());

        try {
            ClaseGeneral.controlAnexosterceros.edit(ClaseGeneral.anexosterceros, anexostercerosId);
        } catch (Exception ex) {
            Logger.getLogger(PanelAnexosterceros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void metodoEliminar() {
        try {
            ClaseGeneral.anexostercerosPK = new AnexostercerosPK();
            ClaseGeneral.anexostercerosPK.setFktercero(fktercero.getText());
            ClaseGeneral.anexostercerosPK.setFecha(fecha.getDate());
            ClaseGeneral.anexostercerosPK.setDocumento("" + documento.getSelectedItem());

            ClaseGeneral.controlAnexosterceros.destroy(ClaseGeneral.anexostercerosPK);
        } catch (Exception ex) {
            Logger.getLogger(PanelAnexosterceros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public final void metodoMostrar() {
        ClaseGeneral.anexosterceros = new Anexosterceros();
        lista = ClaseGeneral.controlAnexosterceros.findAllInAnexostercerosByFktercero(fktercero.getText());

        for (int i = 0; i < 100; i++) {
            jTable.setValueAt("", i, 0);
            jTable.setValueAt("", i, 1);
            jTable.setValueAt("", i, 2);
        }

        int i = 0;
        for (Object lista1 : lista) {
            ClaseGeneral.anexosterceros = (Anexosterceros) lista1;
            jTable.setValueAt("" + ClaseGeneral.anexosterceros.getAnexostercerosPK().getDocumento(), i, 0);
            jTable.setValueAt("" + ClaseGeneral.anexosterceros.getAnexostercerosPK().getFecha(), i, 1);
            jTable.setValueAt("" + ClaseGeneral.anexosterceros.getArchivo(), i, 2);
            i++;
        }

        jTable.clearSelection();
        jTable.getColumnModel().getColumn(0).setPreferredWidth(250);
        jTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable.getColumnModel().getColumn(2).setPreferredWidth(460);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField archivo;
    private javax.swing.JButton botonExaminar;
    private javax.swing.JButton botonVer;
    private javax.swing.JTextField descripcion;
    private javax.swing.JComboBox documento;
    private org.jdesktop.swingx.JXDatePicker fecha;
    private javax.swing.JTextField fktercero;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    public javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    public javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField28;
    // End of variables declaration//GEN-END:variables
}
