/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelAnexoscontratos.java
 *
 * Created on 16/01/2012, 05:14:48 PM
 */
package frame;

import clases.ClaseGeneral;
import clases.ClaseInformacion;
import clases.ClaseMensaje;
import entidades.Anexoscontratos;
import entidades.AnexoscontratosPK;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.net.URL;
import java.net.URLConnection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import neuranas.SFTP;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Jhon Lopez
 */
public class PanelAnexoscontratos extends javax.swing.JPanel {

    private List lista = new ArrayList();
    private ClaseInformacion informacion = new ClaseInformacion();
    FileNameExtensionFilter filter = new FileNameExtensionFilter("pdf", "PDF");
    private File file = null;
    private SFTP sftp = new SFTP();

    /**
     * Creates new form PanelAnexoscontratos
     */
    public PanelAnexoscontratos() {
        initComponents();

        documento.setEditable(true);
        AutoCompleteDecorator.decorate(documento);

        fecha.setFormats(new SimpleDateFormat("yyyy-MM-dd"));
        fecha.setDate(new Date(ClaseInformacion.calendario.getTimeInMillis()));

        fkcontrato.setText(ClaseGeneral.contratos.getContrato());

        /**/        file = null;
        metodoMostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        jLabel = new javax.swing.JLabel();
        fkcontrato = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        documento = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        fecha = new org.jdesktop.swingx.JXDatePicker();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        archivo = new javax.swing.JTextField();
        botonExaminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        botonVer = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        jFileChooser.setCurrentDirectory(new java.io.File("C:\\Users\\Admin\\Documents\\Mis escaneos"));
        jFileChooser.setFileFilter(filter);

        setName("panelAnexoscontratos"); // NOI18N
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel.setText("NÚMERO DEL CONTRATO : ");
        jLabel.setPreferredSize(new java.awt.Dimension(160, 25));
        add(jLabel);

        fkcontrato.setBackground(ClaseGeneral.verde);
        fkcontrato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fkcontrato.setForeground(ClaseGeneral.rojo);
        fkcontrato.setFocusable(false);
        fkcontrato.setMargin(new java.awt.Insets(2, 4, 2, 4));
        fkcontrato.setName("fkcontrato"); // NOI18N
        fkcontrato.setPreferredSize(new java.awt.Dimension(300, 25));
        add(fkcontrato);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setEnabled(false);
        jTextField1.setFocusable(false);
        jTextField1.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField1.setOpaque(false);
        jTextField1.setPreferredSize(new java.awt.Dimension(340, 25));
        add(jTextField1);

        jLabel2.setText("TIPO DOCUMENTO : ");
        jLabel2.setPreferredSize(new java.awt.Dimension(130, 25));
        add(jLabel2);

        documento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        documento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "__________________________", "Estudio del Sector", "Estudios Previos", "Estimación del Presupuesto", "Ficha Técnica", "Invitación Mínima Cuantía", "Informe de Evaluación", "Orden Contractual", "Acta de Aprobación de Pólizas", "Acta de Designación de Supervisor", "Informe de Supervisión", "Convocatoria a Veedurías", "Acta de Inicio", "Acta de Seguimiento", "Acta de Suspensión", "Acta de Finalización", "Acta de Liquidación", "__________________________", "Solicitud de Oferta", "Cotización", "Informe de Recomendación", "__________________________", "Observación", "__________________________", "Documento Adicional", " " }));
        documento.setPreferredSize(new java.awt.Dimension(410, 25));
        add(documento);

        jLabel3.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jLabel3);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jSeparator1);

        jLabel4.setText("FECHA : ");
        jLabel4.setPreferredSize(new java.awt.Dimension(60, 25));
        add(jLabel4);

        fecha.setFocusable(false);
        fecha.setMaximumSize(new java.awt.Dimension(120, 25));
        fecha.setMinimumSize(new java.awt.Dimension(120, 25));
        fecha.setPreferredSize(new java.awt.Dimension(120, 25));
        add(fecha);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setEnabled(false);
        jTextField2.setFocusable(false);
        jTextField2.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jTextField2.setOpaque(false);
        jTextField2.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jTextField2);

        jLabel5.setText("RUTA ARCHIVO : ");
        jLabel5.setPreferredSize(new java.awt.Dimension(105, 25));
        add(jLabel5);

        archivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        archivo.setMargin(new java.awt.Insets(2, 4, 2, 4));
        archivo.setPreferredSize(new java.awt.Dimension(510, 25));
        add(archivo);

        botonExaminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos24/attachment.png"))); // NOI18N
        botonExaminar.setFocusable(false);
        botonExaminar.setPreferredSize(new java.awt.Dimension(25, 24));
        botonExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExaminarActionPerformed(evt);
            }
        });
        add(botonExaminar);

        jLabel6.setPreferredSize(new java.awt.Dimension(15, 25));
        add(jLabel6);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setPreferredSize(new java.awt.Dimension(20, 25));
        add(jSeparator2);

        botonVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos24/text_page.png"))); // NOI18N
        botonVer.setText("Ver pdf");
        botonVer.setFocusable(false);
        botonVer.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonVer.setPreferredSize(new java.awt.Dimension(110, 24));
        botonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerActionPerformed(evt);
            }
        });
        add(botonVer);

        jLabel7.setText("DESCRIPCION : ");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 25));
        add(jLabel7);

        descripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descripcion.setMargin(new java.awt.Insets(2, 4, 2, 4));
        descripcion.setPreferredSize(new java.awt.Dimension(705, 25));
        add(descripcion);

        jLabel8.setPreferredSize(new java.awt.Dimension(810, 25));
        add(jLabel8);

        jScrollPane.setPreferredSize(new java.awt.Dimension(810, 415));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "TIPO ANEXO", "FECHA", "ARCHIVO"
            }
        ));
        jTable.setEnabled(false);
        jTable.setFocusable(false);
        jTable.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTable.setRowHeight(20);
        jTable.setSelectionBackground(ClaseGeneral.campo);
        jScrollPane.setViewportView(jTable);

        add(jScrollPane);
    }// </editor-fold>//GEN-END:initComponents

    private void botonExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExaminarActionPerformed
        try {
            int accion = jFileChooser.showOpenDialog(this);
            if (accion == JFileChooser.APPROVE_OPTION) {
                file = jFileChooser.getSelectedFile();
                archivo.setText(file.getPath());
            } else {
            }
        } catch (Exception e) {
            ClaseMensaje.error("Error al abrir el archivo.\n" + e);
        }
    }//GEN-LAST:event_botonExaminarActionPerformed

    private void botonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerActionPerformed
        try {
            if (file != null) {
                Desktop.getDesktop().open(this.file);
            } else {
                URL url = new URL(ClaseGeneral.servidor + "/UmVbZxut/archivos/" + archivo.getText());
                String extension = archivo.getText().substring(archivo.getText().lastIndexOf("."));
                URLConnection urlCon = url.openConnection();
                InputStream is = urlCon.getInputStream();
                long aleatorio = ClaseInformacion.LongAletario();
                FileOutputStream fos = new FileOutputStream("archivo_" + aleatorio + "" + extension);
                byte[] array = new byte[10000];
                int leido = is.read(array);
                while (leido > 0) {
                    fos.write(array, 0, leido);
                    leido = is.read(array);
                }

                is.close();
                fos.close();

                File file = new File("archivo_" + aleatorio + "" + extension);
                if (file.getAbsoluteFile().exists()) {
                    Desktop.getDesktop().open(file);
                } else {
                }
            }
        } catch (Exception e) {
            ClaseMensaje.error("Error al abrir el archivo.\n" + e);
        }
    }//GEN-LAST:event_botonVerActionPerformed

    public void metodoInsertar() {
        try {
            String extension = archivo.getText().substring(archivo.getText().lastIndexOf("."));
            String nombreArchivo = fkcontrato.getText() + "_" + documento.getSelectedItem() + "_" + ClaseInformacion.ConvertirFecha(fecha.getDate());
            nombreArchivo = nombreArchivo.toUpperCase().trim().replace(" ", "").replace(":", "") + "" + extension;
            nombreArchivo = ClaseInformacion.EliminarAcentosYDemas(nombreArchivo);
            sftp.subir(file.getPath(), nombreArchivo);
            archivo.setText(nombreArchivo);
        } catch (Exception ex) {
            Logger.getLogger(PanelAnexoscontratos.class.getName()).log(Level.SEVERE, null, ex);
        }

        ClaseGeneral.anexoscontratos = new Anexoscontratos();
        ClaseGeneral.anexoscontratosPK = new AnexoscontratosPK();
        ClaseGeneral.anexoscontratosPK.setFkcontrato(fkcontrato.getText());
        ClaseGeneral.anexoscontratosPK.setFecha(fecha.getDate());
        ClaseGeneral.anexoscontratosPK.setDocumento("" + documento.getSelectedItem());
        ClaseGeneral.anexoscontratos.setAnexoscontratosPK(ClaseGeneral.anexoscontratosPK);
        ClaseGeneral.anexoscontratos.setArchivo(archivo.getText());
        ClaseGeneral.anexoscontratos.setDescripcion(descripcion.getText());

        try {
            ClaseGeneral.controlAnexoscontratos.create(ClaseGeneral.anexoscontratos);
        } catch (Exception ex) {
            Logger.getLogger(PanelAnexoscontratos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void metodoConsultar() {
        try {
            fkcontrato.setText(ClaseGeneral.anexoscontratos.getAnexoscontratosPK().getFkcontrato());
            documento.setSelectedItem(ClaseGeneral.anexoscontratos.getAnexoscontratosPK().getDocumento());
            fecha.setDate(ClaseGeneral.anexoscontratos.getAnexoscontratosPK().getFecha());
            archivo.setText(ClaseGeneral.anexoscontratos.getArchivo());
            descripcion.setText(ClaseGeneral.anexoscontratos.getDescripcion());

            fkcontrato.setFocusable(false);
            documento.setEnabled(false);
            fecha.setEditable(false);
            archivo.setFocusable(false);
            botonExaminar.setEnabled(false);
        } catch (Exception ex) {
            Logger.getLogger(PanelResoluciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void metodoActualizar() {
        Anexoscontratos anexoscontratosId = ClaseGeneral.anexoscontratos;
        anexoscontratosId.setAnexoscontratosPK(ClaseGeneral.anexoscontratos.getAnexoscontratosPK());
        ClaseGeneral.anexoscontratos = new Anexoscontratos();
        ClaseGeneral.anexoscontratosPK = new AnexoscontratosPK();
        ClaseGeneral.anexoscontratosPK.setFkcontrato(fkcontrato.getText());
        ClaseGeneral.anexoscontratosPK.setFecha(fecha.getDate());
        ClaseGeneral.anexoscontratosPK.setDocumento("" + documento.getSelectedItem());
        ClaseGeneral.anexoscontratos.setAnexoscontratosPK(ClaseGeneral.anexoscontratosPK);
        ClaseGeneral.anexoscontratos.setArchivo(archivo.getText());
        ClaseGeneral.anexoscontratos.setDescripcion(descripcion.getText());

        try {
            ClaseGeneral.controlAnexoscontratos.edit(ClaseGeneral.anexoscontratos, anexoscontratosId);
        } catch (Exception ex) {
            Logger.getLogger(PanelAnexoscontratos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void metodoEliminar() {
        try {
            ClaseGeneral.anexoscontratosPK = new AnexoscontratosPK();
            ClaseGeneral.anexoscontratosPK.setFkcontrato(fkcontrato.getText());
            ClaseGeneral.anexoscontratosPK.setFecha(fecha.getDate());
            ClaseGeneral.anexoscontratosPK.setDocumento("" + documento.getSelectedItem());

            ClaseGeneral.controlAnexoscontratos.destroy(ClaseGeneral.anexoscontratosPK);
        } catch (Exception ex) {
            Logger.getLogger(PanelAnexoscontratos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public final void metodoMostrar() {
        ClaseGeneral.anexoscontratos = new Anexoscontratos();
        lista = ClaseGeneral.controlAnexoscontratos.findAllInAnexoscontratosByFkcontrato(fkcontrato.getText());

        for (int i = 0; i < 100; i++) {
            jTable.setValueAt("", i, 0);
            jTable.setValueAt("", i, 1);
            jTable.setValueAt("", i, 2);
        }

        int i = 0;
        for (Object lista1 : lista) {
            ClaseGeneral.anexoscontratos = (Anexoscontratos) lista1;
            jTable.setValueAt("" + ClaseGeneral.anexoscontratos.getAnexoscontratosPK().getDocumento(), i, 0);
            jTable.setValueAt("" + ClaseGeneral.anexoscontratos.getAnexoscontratosPK().getFecha(), i, 1);
            jTable.setValueAt("" + ClaseGeneral.anexoscontratos.getArchivo(), i, 2);
            i++;
        }

        jTable.clearSelection();
        jTable.getColumnModel().getColumn(0).setPreferredWidth(250);
        jTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable.getColumnModel().getColumn(2).setPreferredWidth(460);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField archivo;
    private javax.swing.JButton botonExaminar;
    private javax.swing.JButton botonVer;
    private javax.swing.JTextField descripcion;
    private javax.swing.JComboBox documento;
    private org.jdesktop.swingx.JXDatePicker fecha;
    private javax.swing.JTextField fkcontrato;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
